#!/usr/bin/env zsh

# Some paths below (eg. Homebrew) may not exist on all platforms.
setopt NULL_GLOB

# Everything in $fpath, regardless of extension.
FILES_TO_COMPILE=()
FILES_TO_COMPILE+=($HOME/.zsh/completions/*)
FILES_TO_COMPILE+=($HOME/.zsh/functions.d/*)
FILES_TO_COMPILE+=($HOME/.zsh/zsh-completions/src/*)
FILES_TO_COMPILE+=(/opt/homebrew/share/zsh/site-functions/*)
FILES_TO_COMPILE+=(/opt/homebrew/Cellar/zsh/5.9/share/zsh/functions/*)

# Other files, targeted by extension.
FILES_TO_COMPILE+=($HOME/.zsh/*.zsh)
FILES_TO_COMPILE+=($HOME/.zsh/host/*.zsh)

# Other third-party submodules.
FILES_TO_COMPILE+=($HOME/.zsh/zsh-autosuggestions/*.zsh)
FILES_TO_COMPILE+=($HOME/.zsh/zsh-syntax-highlighting/*.zsh)
FILES_TO_COMPILE+=($HOME/.zsh/zsh-history-substring-search/*.zsh)

# Adding these ones manually for now, until I decide what to do with them.
FILES_TO_COMPILE+=($HOME/.zshrc)
FILES_TO_COMPILE+=($HOME/.zsh/zshenv)
FILES_TO_COMPILE+=($HOME/.zsh/zshrc)

for FILE in $FILES_TO_COMPILE; do
  if [[ ! "${FILE}" == *.zwc ]]; then
    echo "-> ${FILE}"
    zcompile -M -- "${FILE}.zwc" "${FILE}"
  fi
done
