#!/usr/bin/env zsh -i

# Third-party submodules.
FILES_TO_COMPILE=()
FILES_TO_COMPILE+=($HOME/.zsh/zsh-autosuggestions/*.zsh)
FILES_TO_COMPILE+=($HOME/.zsh/zsh-syntax-highlighting/*.zsh)
FILES_TO_COMPILE+=($HOME/.zsh/zsh-history-substring-search/*.zsh)

# Add everything in $fpath, regardless of extension.
for DIR in $fpath; do
  if [[ -d $DIR ]]; then
    FILES_TO_COMPILE+=("${DIR}"/*)
  fi
done

# Adding these ones manually for now, until I decide what to do with them.
# Most things except encrypted files and the main .zshrc/.zshenv.
FILES_TO_COMPILE+=($HOME/.zsh/aliases)
FILES_TO_COMPILE+=($HOME/.zsh/color)
FILES_TO_COMPILE+=($HOME/.zsh/common)
FILES_TO_COMPILE+=($HOME/.zsh/exports)
FILES_TO_COMPILE+=($HOME/.zsh/functions)
FILES_TO_COMPILE+=($HOME/.zsh/hash)
FILES_TO_COMPILE+=($HOME/.zsh/host/huertas)
FILES_TO_COMPILE+=($HOME/.zsh/host/latina)
FILES_TO_COMPILE+=($HOME/.zsh/host/retiro)
FILES_TO_COMPILE+=($HOME/.zsh/path)
FILES_TO_COMPILE+=($HOME/.zsh/skim/shell/completion.zsh)
FILES_TO_COMPILE+=($HOME/.zsh/vars)

for FILE in $FILES_TO_COMPILE; do
  if [[ ! "${FILE}" == *.zwc ]]; then
    echo "-> ${FILE}"
    zcompile -R -- "${FILE}.zwc" "${FILE}"
  fi
done

exit
