# install with `brew bundle`

install ack
install apple-gcc42
install autoconf
install automake
install clipper
install cmake
install ctags
install elinks
install freetype
install gdbm
install git
install gnupg
install go
install gpg-agent
install htop-osx
install imagemagick
install jpeg
install libassuan
install libevent
install libgcrypt
install libgpg-error
install libksba
install libpng
install libtool
install libyaml
install links
install mariadb
install memcached
install mercurial
install mldonkey
install nginx
install node
install objective-caml
install openssl
install optipng
install pcre
install pinentry
install pkg-config
install pngquant
install pstree
install pth
install pwgen
install qt
install ragel
install rbenv
install readline
install redis
install rhino
install ruby-build
install s3cmd
install the_silver_searcher
install tig
install tmux
install tree
install vim
install watch
install wget
install xz
install zsh
