# install with `brew bundle`

install ack
install ant
install apple-gcc42
install autoconf
install automake
install clipper
install cloc
install cloog
install closure-compiler
install cmake
install cscope
install ctags
install elinks
install fontconfig
install freetype
install gcc
install gd
install gdbm
install gettext
install git --with-pcre
install glib
install gmp
install gnupg
install gnutls
install go
install gpg-agent
install htop-osx
install iftop
install imagemagick
install isl
install jpeg
install json-c
install libassuan
install libevent
install libffi
install libgcrypt
install libgpg-error
install libksba
install libmpc
install libpng
install libtasn1
install libtiff
install libtool
install libyaml
install libyubikey
install links
install macvim
install makedepend
install mariadb
install memcached
install mercurial
install mldonkey
install mobile-shell
install mpfr
install nettle
install nginx
install node
install objective-caml
install openssl
install optipng
install ossp-uuid
install pcre
install pinentry
install pixman
install pkg-config
install pngquant
install postgresql
install protobuf
install pstree
install pth
install pwgen
install qemu
install qt
install ragel
install rbenv
install readline
install redis
install rhino
install ruby-build
install s3cmd
install the_silver_searcher
install tig
install tmux
install tree
install valgrind
install vim
install watch
install watchman
install wget
install xz
install ykpers
install zsh
