#!/bin/bash

set -e

REPO_ROOT="${BASH_SOURCE%/*}"

source "$REPO_ROOT/bin/common"

log_info "Installing TypeScript"

yarn --frozen-lockfile --no-default-rc --no-progress --silent

log_info "Cleaning"

git clean -fq -- "$REPO_ROOT"/lib
git clean -fq -- "$REPO_ROOT"/src/types

log_info "Generating TypeScript types"

node "$REPO_ROOT/support/typegen"

log_info "Compiling TypeScript source to JavaScript"

tsc

log_info "Running main"

node "$REPO_ROOT/lib/src/main.js" "$@"
