#!/bin/bash

set -e

REPO_ROOT="${BASH_SOURCE%/*}"

cd "$REPO_ROOT"

source bin/common

log_info "Installing TypeScript"

yarn --frozen-lockfile --no-default-rc --no-progress --silent

# TODO: may not need this with Yarn workspaces
(cd node_modules && ln -s ../lib/src fig)

log_info "Cleaning"

git clean -fq -- lib
git clean -fq -- src/types

log_info "Generating TypeScript types"

node support/typegen

log_info "Compiling TypeScript source to JavaScript"

tsc

log_info "Running main"

node lib/src/main.js "$@"
