#!/bin/bash

set -e

REPO_ROOT="${BASH_SOURCE%/*}"
BIN_DIR="$REPO_ROOT/bin"
NODE_EXE="$BIN_DIR/node"
YARN_EXE="$BIN_DIR/yarn"
MAIN_EXE="$REPO_ROOT/lib/main.js"

echo "[status] Installing TypeScript"

"$YARN_EXE" --frozen-lockfile --no-default-rc --no-progress --silent

echo "[status] Building"

"$YARN_EXE" run --silent tsc

echo "[status] Running main"

"$NODE_EXE" "$MAIN_EXE" "$@"
