#!/bin/sh

set -x

# [10.11.1]
defaults -currentHost write com.apple.systemuiserver dontAutoLoad -array \
  "/Applications/Utilities/Keychain Access.app/Contents/Resources/Keychain.menu" \
  "/System/Library/CoreServices/Menu Extras/Battery.menu" \
  "/System/Library/CoreServices/Menu Extras/Clock.menu" \
  "/System/Library/CoreServices/Menu Extras/TimeMachine.menu" \
  "/System/Library/CoreServices/Menu Extras/Volume.menu"

# [10.11.1]
defaults write com.apple.systemuiserver menuExtras -array \
  "/System/Library/CoreServices/Menu Extras/AirPort.menu" \
  "/System/Library/CoreServices/Menu Extras/Bluetooth.menu" \
  "/System/Library/CoreServices/Menu Extras/TextInput.menu"

# [10.11.1] Show the ~/Library folder
chflags nohidden ~/Library

# [10.9] Misc `systemsetup` settings: see `man systemsetup`
sudo systemsetup -settimezone US/Pacific
sudo systemsetup -setusingnetworktime on
sudo systemsetup -setcomputersleep Never
sudo systemsetup -setdisplaysleep 15
sudo systemsetup -setharddisksleep Never
sudo systemsetup -setrestartfreeze on
sudo systemsetup -setremoteappleevents off

# [10.9] Disable the sudden motion sensor as it’s not useful for SSDs
# [Probably useless; no way to verify this command works]
sudo pmset -a sms 0

# [10.9] Disable local Time Machine snapshots
sudo tmutil disable
sudo tmutil disablelocal
