#!/bin/sh

set -x

# Many of these settings taken (or modified) from:

#   https://github.com/mathiasbynens/dotfiles/commits/master/.osx
#
# Numbers in square brackets indicate system version on which these settings
# were last verified to work.

# [10.9] Tweak subpixel font rendering (https://wincent.com/wiki/AppleFontSmoothing)
defaults -currentHost write NSGlobalDomain AppleFontSmoothing -int 1

# [10.10] System Preferences -> Accessibility -> Display -> Reduce Transparency
defaults write com.apple.universalaccess reduceTransparency -bool true

# [10.10] System Preferences -> General -> Appearance -> Graphite
# (default is 1, "Blue")
defaults write NSGlobalDomain AppleAquaColorVariant -int 6

# [10.10.2] System Preferences -> General -> Sidebar icon size -> Small
defaults write NSGlobalDomain NSTableViewDefaultSizeMode -int 1

# [10.10.2] System Preferences -> General -> Show scroll bars ->
# Automatically based on mouse or trackpad
defaults write NSGlobalDomain AppleShowScrollBars Automatic

# [10.10.2] System Preferences -> General -> Click in scroll bar to ->
# Jump to the next page
defaults write NSGlobalDomain AppleScrollerPagingBehavior -int 0

# [10.10.2] System Preferences -> General ->
# [Don't] Ask to keep changes when closing documents
defaults write NSGlobalDomain NSCloseAlwaysConfirmsChanges -int 0

# [10.10.2] System Preferences -> General ->
# [Don't] Close windows when quitting an app
defaults write NSGlobalDomain NSQuitAlwaysKeepsWindows -int 0

# [10.10.2] System Preferences -> General -> Recent items
defaults write com.apple.recentitems RecentApplications -dict-add MaxAmount 50
defaults write com.apple.recentitems RecentDocuments -dict-add MaxAmount 50
defaults write com.apple.recentitems RecentServers -dict-add MaxAmount 50

# [10.9] Expand save panel by default
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

# [10.10.2] Make sheets drop down (almost) instantly
defaults write NSGlobalDomain NSWindowResizeTime -float 0.001

# [10.10.2] System Preferences -> Desktop & Screen Saver -> Screen Saver ->
# Show with clock
defaults -currentHost write com.apple.screensaver showClock -int 1

# [10.10.2] System Preferences -> Desktop & Screen Saver -> Screen Saver ->
# Start after -> 5 Minutes
defaults -currentHost write com.apple.screensaver idleTime -int 300

# [10.10.2] System Preferences -> Desktop & Screen Saver -> Screen Saver ->
# Hot Corners -> [Bottom Left] Start Screen Saver
defaults write com.apple.dock wvous-bl-corner -int 5

# [10.10.2] System Preferences -> Desktop & Screen Saver -> Screen Saver ->
# Hot Corners -> [Top Right] Disable Screen Saver
defaults write com.apple.dock wvous-tr-corner -int 6

 # [10.9] Expand print panel by default
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint2 -bool true

# [10.10.2] System Preferences -> Sound -> Sound Effects -> Play feedback when
# volume is changed
defaults write NSGlobalDomain com.apple.sound.beep.feedback -bool false

# [10.10.2] Finder -> Preferences -> General -> Spring-loaded folders and
# windows -> Delay (short)
defaults write NSGlobalDomain com.apple.springing.delay -float 0

# [10.10.2] Finder -> Preferences -> General -> Spring-loaded folders and
# windows
defaults write NSGlobalDomain com.apple.springing.enabled -bool true

# [10.9] Use plain text mode for new TextEdit documents
defaults write com.apple.TextEdit RichText -int 0

# [10.9] Disable press-and-hold for keys in favor of key repeat
# Requires logout.
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

# [10.9] Show the ~/Library folder
chflags nohidden ~/Library

# [10.9] Finder: disable window animations and Get Info animations
defaults write com.apple.finder DisableAllAnimations -bool true

# [10.9] Finder: allow text selection in Quick Look
defaults write com.apple.finder QLEnableTextSelection -bool true

# [10.9] Disable the warning when changing a file extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# [10.9] Disable smart quotes, dashes, ellipses
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

# [10.9] Disable auto-correct
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

# [10.9] Finder: show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# [10.9] Finder: allow quitting via Command-Q; doing so will also hide desktop icons
defaults write com.apple.finder QuitMenuItem -bool true

# [10.9] [Don't] display full POSIX path as Finder window title
defaults write com.apple.finder _FXShowPosixPathInTitle -bool false

# [10.9] Finder: show status bar
defaults write com.apple.finder ShowStatusBar -bool true

# [10.9] Finder: show path bar
defaults write com.apple.finder ShowPathbar -bool true

# [10.9] Require password immediately after sleep or screen saver begins
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0

# [10.9] Automatically quit printer app once the print jobs complete
defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

# [10.9] Misc `systemsetup` settings: see `man systemsetup`
sudo systemsetup -settimezone America/Los_Angeles
sudo systemsetup -setusingnetworktime on
sudo systemsetup -setcomputersleep 60
sudo systemsetup -setdisplaysleep 15
sudo systemsetup -setharddisksleep Never
sudo systemsetup -setrestartfreeze on
sudo systemsetup -setremoteappleevents off

# [10.9] Disable the sudden motion sensor as it’s not useful for SSDs
# [Probably useless; no way to verify this command works]
sudo pmset -a sms 0

# [10.9] Disable local Time Machine snapshots
sudo tmutil disable
sudo tmutil disablelocal
