#!/bin/sh

set -x

# [10.9] Show the ~/Library folder
chflags nohidden ~/Library

# [10.9] Misc `systemsetup` settings: see `man systemsetup`
sudo systemsetup -settimezone America/Los_Angeles
sudo systemsetup -setusingnetworktime on
sudo systemsetup -setcomputersleep 60
sudo systemsetup -setdisplaysleep 15
sudo systemsetup -setharddisksleep Never
sudo systemsetup -setrestartfreeze on
sudo systemsetup -setremoteappleevents off

# [10.9] Disable the sudden motion sensor as it’s not useful for SSDs
# [Probably useless; no way to verify this command works]
sudo pmset -a sms 0

# [10.9] Disable local Time Machine snapshots
sudo tmutil disable
sudo tmutil disablelocal
