# Scheme name: Square
# Scheme author: FredHappyface (https://github.com/fredHappyface)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base24-square
ColorForeground=#bababa
ColorBackground=#1a1a1a
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#050505;#e9897c;#b6377d;#b6defb;#a9cdeb;#75507b;#c9caec;#f2f2f2;#141414;#f99286;#c3f786;#fcfbcc;#b6defb;#ad7fa8;#d7d9fc;#e2e2e2
