# Scheme name: Silk Dark
# Scheme author: Gabriel Fontes (https://github.com/Misterio77)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-silk-dark
ColorForeground=#c7dbdd
ColorBackground=#0e3c46
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1d494e;#fb6953;#73d8ad;#fce380;#46bddd;#756b8a;#3fb2b9;#cbf2f7;#2a5054;#fb6953;#73d8ad;#fce380;#46bddd;#756b8a;#3fb2b9;#d2faff
