# Scheme name: Da One Paper
# Scheme author: NNB (https://github.com/NNBnh)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-da-one-paper
ColorForeground=#181818
ColorBackground=#faf0dc
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#c8c8c8;#de5d6e;#76a85d;#b3684f;#5890f8;#c173d1;#64b5a7;#000000;#888888;#de5d6e;#76a85d;#b3684f;#5890f8;#c173d1;#64b5a7;#000000
