# Scheme name: Bluloco Dark
# Scheme author: FredHappyface (https://github.com/fredHappyface)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base24-bluloco-dark
ColorForeground=#b1bac9
ColorBackground=#1e2027
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#494f5c;#f71041;#23974a;#189ffd;#285afe;#8c62fd;#366f99;#ccd5e4;#60697a;#fb496d;#37bc58;#f6bd47;#189ffd;#fb57f6;#4fabad;#fefefe
