# Scheme name: Nocturnal Winter
# Scheme author: FredHappyface (https://github.com/fredHappyface)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base24-nocturnal-winter
ColorForeground=#dcdcdc
ColorBackground=#0d0d17
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#4c4c4c;#f12d52;#08cd7d;#6095fe;#3081df;#fe2a6c;#09c87a;#fbfbfb;#7f7f7f;#f16c85;#0ae78d;#fefb67;#6095fe;#ff78a2;#0ae78d;#ffffff
