# Scheme name: Apathy
# Scheme author: Jannik Siebert (https://github.com/janniks)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-apathy
ColorForeground=#81b5ac
ColorBackground=#031a16
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#0b342d;#3e9688;#883e96;#3e4c96;#96883e;#4c963e;#963e4c;#a7cec8;#184e45;#3e9688;#883e96;#3e4c96;#96883e;#4c963e;#963e4c;#d2e7e4
