# Scheme name: Atelier Sulphurpool
# Scheme author: FredHappyface (https://github.com/fredHappyface)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base24-atelier-sulphurpool
ColorForeground=#8c92ac
ColorBackground=#202746
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#202746;#c94922;#ac9739;#898ea4;#3d8fd1;#6679cc;#22a2c9;#979db4;#6b7394;#c76b29;#293256;#5e6687;#898ea4;#dfe2f1;#9c637a;#f5f7ff
