# Scheme name: Charcoal Light
# Scheme author: Mubin Muhammad (https://github.com/mubin6th)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-charcoal-light
ColorForeground=#35291d
ColorBackground=#d6b891
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#c0a179;#413325;#120f09;#292016;#120f09;#292016;#413325;#413325;#a28662;#413325;#120f09;#292016;#120f09;#292016;#413325;#d6b891
