# Scheme name: Rebecca
# Scheme author: Victor Borja (http://github.com/vic) based on Rebecca Theme (http://github.com/vic/rebecca-theme)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-rebecca
ColorForeground=#f1eff8
ColorBackground=#292a44
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#663399;#a0a0c5;#6dfedf;#ae81ff;#2de0a7;#7aa5ff;#8eaee0;#ccccff;#383a62;#a0a0c5;#6dfedf;#ae81ff;#2de0a7;#7aa5ff;#8eaee0;#53495d
