# Scheme name: Solarized Dark
# Scheme author: Ethan Schoonover (modified by aramisgithub)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-solarized-dark
ColorForeground=#93a1a1
ColorBackground=#002b36
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#073642;#dc322f;#859900;#b58900;#268bd2;#6c71c4;#2aa198;#eee8d5;#586e75;#dc322f;#859900;#b58900;#268bd2;#6c71c4;#2aa198;#fdf6e3
