# Scheme name: Chicago Day
# Scheme author: Wendell, Ryan &lt;ryanjwendell@gmail.com&gt;
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-chicago-day
ColorForeground=#364c40
ColorBackground=#e8f0ea
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#d1e0d7;#c60c30;#009b3a;#968400;#522398;#e27ea6;#00a1de;#2a3b32;#b9d0c3;#c60c30;#009b3a;#968400;#522398;#e27ea6;#00a1de;#1e2a24
