# Scheme name: Gruvbox Material Light, Hard
# Scheme author: Mayush Kumar (https://github.com/MayushKumar), sainnhe (https://github.com/sainnhe/gruvbox-material-vscode)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-gruvbox-material-light-hard
ColorForeground=#654735
ColorBackground=#f9f5d7
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#fbf1c7;#c14a4a;#6c782e;#b47109;#45707a;#945e80;#4c7a5d;#3c3836;#e0cfa9;#c14a4a;#6c782e;#b47109;#45707a;#945e80;#4c7a5d;#282828
