# Scheme name: Cobalt2
# Scheme author: FredHappyface (https://github.com/fredHappyface)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base24-cobalt2
ColorForeground=#a1a1a1
ColorBackground=#122637
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#000000;#ff0000;#37dd21;#5555ff;#1460d2;#ff005d;#00bbbb;#bbbbbb;#555555;#f40d17;#3bcf1d;#ecc809;#5555ff;#ff55ff;#6ae3f9;#ffffff
