# Scheme name: One Light
# Scheme author: FredHappyface (https://github.com/fredHappyface)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base24-one-light
ColorForeground=#383a42
ColorBackground=#e7e7e9
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#dfdfe1;#ca1243;#50a14f;#febb2a;#4078f2;#a626a4;#0184bc;#202227;#cacace;#ec2258;#6db76c;#f4a701;#709af5;#d02fcd;#01a7ef;#090a0b
