# Scheme name: Synth Midnight Terminal Light
# Scheme author: Michaël Ball (http://github.com/michael-ball/)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-synth-midnight-light
ColorForeground=#28292a
ColorBackground=#dddfe0
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#cfd1d2;#b53b50;#06ea61;#c9d364;#03aeff;#ea5ce2;#42fff9;#1a1b1c;#c1c3c4;#b53b50;#06ea61;#c9d364;#03aeff;#ea5ce2;#42fff9;#050608
