# Scheme name: One Light
# Scheme author: Daniel Pfeifer (http://github.com/purpleKarrot)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-one-light
ColorForeground=#383a42
ColorBackground=#fafafa
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#f0f0f1;#ca1243;#50a14f;#c18401;#4078f2;#a626a4;#0184bc;#202227;#e5e5e6;#ca1243;#50a14f;#c18401;#4078f2;#a626a4;#0184bc;#090a0b
