# Scheme name: Elemental
# Scheme author: FredHappyface (https://github.com/fredHappyface)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base24-elemental
ColorForeground=#756f68
ColorBackground=#21211c
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#3c3b30;#97280f;#479942;#78d8d8;#497f7d;#7e4e2e;#387f58;#807974;#545444;#df502a;#60e06f;#d69827;#78d8d8;#cd7c53;#58d598;#fff1e8
