# Scheme name: Flat
# Scheme author: FredHappyface (https://github.com/fredHappyface)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base24-flat
ColorForeground=#8c939a
ColorBackground=#082845
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1d2845;#a82320;#2d9440;#3c7dd2;#3167ac;#781aa0;#2c9370;#b0b6ba;#2e2e45;#d4312e;#32a548;#e5be0c;#3c7dd2;#8230a7;#35b387;#e7eced
