# Scheme name: Tango
# Scheme author: @Schnouki, based on the Tango Desktop Project
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-tango
ColorForeground=#d3d7cf
ColorBackground=#2e3436
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#8ae234;#cc0000;#4e9a06;#c4a000;#3465a4;#75507b;#06989a;#ad7fa8;#fce94f;#cc0000;#4e9a06;#c4a000;#3465a4;#75507b;#06989a;#eeeeec
