# Scheme name: Horizon Terminal Dark
# Scheme author: Michaël Ball (http://github.com/michael-ball/)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-horizon-terminal-dark
ColorForeground=#cbced0
ColorBackground=#1c1e26
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#232530;#e95678;#29d398;#fac29a;#26bbd9;#ee64ac;#59e1e3;#dcdfe4;#2e303e;#e95678;#29d398;#fac29a;#26bbd9;#ee64ac;#59e1e3;#e3e6ee
