# Scheme name: caroline
# Scheme author: ed (https://codeberg.org/ed)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-caroline
ColorForeground=#a87569
ColorBackground=#1c1213
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#3a2425;#c24f57;#806c61;#f28171;#684c59;#a63650;#6b6566;#c58d7b;#563837;#c24f57;#806c61;#f28171;#684c59;#a63650;#6b6566;#e3a68c
