# Scheme name: Material Vivid
# Scheme author: joshyrobot
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-material-vivid
ColorForeground=#80868b
ColorBackground=#202124
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#27292c;#f44336;#00e676;#ffeb3b;#2196f3;#673ab7;#00bcd4;#9e9e9e;#323639;#f44336;#00e676;#ffeb3b;#2196f3;#673ab7;#00bcd4;#ffffff
