# Scheme name: Ayu Light
# Scheme author: Tinted Theming (https://github.com/tinted-theming), Ayu Theme (https://github.com/ayu-theme)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base24-ayu-light
ColorForeground=#5c6166
ColorBackground=#f8f9fa
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#edeff1;#f07171;#6cbf49;#f2ae49;#399ee6;#a37acc;#4cbf99;#4e5257;#d2d4d8;#ff7383;#86b300;#ffaa33;#478acc;#b595d6;#55b4d4;#404447
