# Scheme name: Rippedcasts
# Scheme author: FredHappyface (https://github.com/fredHappyface)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base24-rippedcasts
ColorForeground=#a8a8a8
ColorBackground=#2b2b2b
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#000000;#cdaf95;#a7ff60;#86bdc9;#75a5b0;#ff73fd;#59647e;#bfbfbf;#666666;#eecbad;#bcee68;#e5e500;#86bdc9;#e500e5;#8c9bc3;#e5e5e5
