# Scheme name: Oxocarbon Light
# Scheme author: shaunsingh/IBM
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-oxocarbon-light
ColorForeground=#393939
ColorBackground=#f2f4f8
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#dde1e6;#ff7eb6;#0f62fe;#ff6f00;#42be65;#be95ff;#673ab7;#525252;#525252;#ff7eb6;#0f62fe;#ff6f00;#42be65;#be95ff;#673ab7;#08bdba
