# Scheme name: Dimmed Monokai
# Scheme author: FredHappyface (https://github.com/fredHappyface)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base24-dimmed-monokai
ColorForeground=#acafac
ColorBackground=#1e1e1e
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#3a3c43;#be3e48;#869a3a;#176ce3;#4e76a1;#855b8d;#568ea3;#b8bcb9;#888987;#fb001e;#0e712e;#c37033;#176ce3;#fb0067;#2d6f6c;#fcffb8
