# Scheme name: Precious Dark Fifteen
# Scheme author: 4lex4 &lt;4lex49@zoho.com&gt;
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-precious-dark-fifteen
ColorForeground=#bab9b6
ColorBackground=#23262b
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#303337;#ff8782;#95b659;#cfa546;#66b0ef;#b799ff;#42bda7;#bab9b6;#3e4044;#ff8782;#95b659;#cfa546;#66b0ef;#b799ff;#42bda7;#bab9b6
