# Scheme name: Tomorrow Night
# Scheme author: Cody Buell (https://github.com/codybuell)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base24-tomorrow-night
ColorForeground=#c5c8c6
ColorBackground=#1d1f21
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#282a2e;#cc6666;#b5bd68;#f0c674;#81a2be;#b294bb;#8abeb7;#e0e0e0;#373b41;#e74c3c;#b8d4b3;#f7dc6f;#85c1e9;#d7a3ca;#95d3ce;#ffffff
