# Scheme name: Da One Gray
# Scheme author: NNB (https://github.com/NNBnh)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-da-one-gray
ColorForeground=#ffffff
ColorBackground=#181818
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#282828;#fa7883;#98c379;#ff9470;#6bb8ff;#e799ff;#8af5ff;#ffffff;#585858;#fa7883;#98c379;#ff9470;#6bb8ff;#e799ff;#8af5ff;#ffffff
