# Scheme name: ShadeSmear Dark
# Scheme author: Kyle Giammarco (http://kyle.giammar.co)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-shadesmear-dark
ColorForeground=#dbdbdb
ColorBackground=#232323
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1c1c1c;#cc5450;#71983b;#307878;#376388;#d7ab54;#c57d42;#e4e4e4;#4e4e4e;#cc5450;#71983b;#307878;#376388;#d7ab54;#c57d42;#1c1c1c
