# Scheme name: Broadcast
# Scheme author: FredHappyface (https://github.com/fredHappyface)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base24-broadcast
ColorForeground=#cbcbcb
ColorBackground=#2b2b2b
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#000000;#da4939;#519f50;#9fcef0;#6d9cbe;#d0d0ff;#6e9cbe;#ffffff;#323232;#ff7b6b;#83d182;#ffff7c;#9fcef0;#ffffff;#a0cef0;#ffffff
