# Scheme name: summercamp
# Scheme author: zoe firi (zoefiri.github.io)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-summercamp
ColorForeground=#736e55
ColorBackground=#1c1810
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#2a261c;#e35142;#5ceb5a;#f2ff27;#489bf0;#ff8080;#5aebbc;#bab696;#3a3527;#e35142;#5ceb5a;#f2ff27;#489bf0;#ff8080;#5aebbc;#f8f5de
