# Scheme name: Tokyo City Terminal Light
# Scheme author: Michaël Ball
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-tokyo-city-terminal-light
ColorForeground=#28323a
ColorBackground=#fbfbfd
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#f6f6f8;#8c4351;#33635c;#8f5e15;#34548a;#5a4a78;#0f4b6e;#1d252c;#d8e2ec;#8c4351;#33635c;#8f5e15;#34548a;#5a4a78;#0f4b6e;#171d23
