# Scheme name: Grayscale Dark
# Scheme author: Alexandre Gavioli (https://github.com/Alexx2/)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-grayscale-dark
ColorForeground=#b9b9b9
ColorBackground=#101010
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#252525;#7c7c7c;#8e8e8e;#a0a0a0;#686868;#747474;#868686;#e3e3e3;#464646;#7c7c7c;#8e8e8e;#a0a0a0;#686868;#747474;#868686;#f7f7f7
