# Scheme name: Monokai
# Scheme author: Wimer Hazenberg (http://www.monokai.nl)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-monokai
ColorForeground=#f8f8f2
ColorBackground=#272822
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#383830;#f92672;#a6e22e;#f4bf75;#66d9ef;#ae81ff;#a1efe4;#f5f4f1;#49483e;#f92672;#a6e22e;#f4bf75;#66d9ef;#ae81ff;#a1efe4;#f9f8f5
