# Scheme name: Atelier Plateau Light
# Scheme author: Bram de Haan (http://atelierbramdehaan.nl)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-atelier-plateau-light
ColorForeground=#585050
ColorBackground=#f4ecec
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#e7dfdf;#ca4949;#4b8b8b;#a06e3b;#7272ca;#8464c4;#5485b6;#292424;#8a8585;#ca4949;#4b8b8b;#a06e3b;#7272ca;#8464c4;#5485b6;#1b1818
