# Scheme name: Eva
# Scheme author: kjakapat (https://github.com/kjakapat)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-eva
ColorForeground=#9fa2a6
ColorBackground=#2a3b4d
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#3d566f;#c4676c;#66ff66;#ffff66;#15f4ee;#9c6cd3;#4b8f77;#d6d7d9;#4b6988;#c4676c;#66ff66;#ffff66;#15f4ee;#9c6cd3;#4b8f77;#ffffff
