# Scheme name: Gruber
# Scheme author: Patel, Nimai &lt;nimai.m.patel@gmail.com&gt;, colors from www.github.com/rexim/gruber-darker-theme
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-gruber
ColorForeground=#f4f4ff
ColorBackground=#181818
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#453d41;#f43841;#73c936;#ffdd33;#96a6c8;#9e95c7;#95a99f;#f5f5f5;#484848;#f43841;#73c936;#ffdd33;#96a6c8;#9e95c7;#95a99f;#e4e4ef
