# Scheme name: OneDark
# Scheme author: Lalit Magant (http://github.com/tilal6991)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-onedark
ColorForeground=#abb2bf
ColorBackground=#282c34
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#353b45;#e06c75;#98c379;#e5c07b;#61afef;#c678dd;#56b6c2;#b6bdca;#3e4451;#e06c75;#98c379;#e5c07b;#61afef;#c678dd;#56b6c2;#c8ccd4
