# Scheme name: Sagelight
# Scheme author: Carter Veldhuizen
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-sagelight
ColorForeground=#383838
ColorBackground=#f8f8f8
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#e8e8e8;#fa8480;#a0d2c8;#ffdc61;#a0a7d2;#c8a0d2;#a2d6f5;#282828;#d8d8d8;#fa8480;#a0d2c8;#ffdc61;#a0a7d2;#c8a0d2;#a2d6f5;#181818
