# Scheme name: Ayu Dark
# Scheme author: Tinted Theming (https://github.com/tinted-theming), Ayu Theme (https://github.com/ayu-theme)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-ayu-dark
ColorForeground=#e6e1cf
ColorBackground=#0b0e14
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#131721;#f07178;#aad94c;#ffb454;#59c2ff;#d2a6ff;#95e6cb;#ece8db;#202229;#f07178;#aad94c;#ffb454;#59c2ff;#d2a6ff;#95e6cb;#f2f0e7
