# Scheme name: Tokyodark Terminal
# Scheme author: Tiagovla (https://github.com/tiagovla/)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-tokyodark-terminal
ColorForeground=#a0a8cd
ColorBackground=#11121d
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1a1b2a;#ee6d85;#95c561;#d7a65f;#7199ee;#a485dd;#38a89d;#a0a8cd;#212234;#ee6d85;#95c561;#d7a65f;#7199ee;#a485dd;#38a89d;#a0a8cd
