# Scheme name: iA Light
# Scheme author: iA Inc. (modified by aramisgithub)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-ia-light
ColorForeground=#181818
ColorBackground=#f6f6f6
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#dedede;#9c5a02;#38781c;#c48218;#48bac2;#a94598;#2d6bb1;#e8e8e8;#bde5f2;#9c5a02;#38781c;#c48218;#48bac2;#a94598;#2d6bb1;#f8f8f8
