# Scheme name: Alien Blood
# Scheme author: FredHappyface (https://github.com/fredHappyface)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base24-alien-blood
ColorForeground=#5a6f5c
ColorBackground=#0f160f
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#112615;#7f2b26;#2f7e25;#00a9df;#2f697f;#47577e;#317f76;#647d75;#3c4711;#df8008;#18e000;#bde000;#00a9df;#0058df;#00dfc3;#73f990
