# Scheme name: Porple
# Scheme author: Niek den Breeje (https://github.com/AuditeMarlow)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-porple
ColorForeground=#d8d8d8
ColorBackground=#292c36
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#333344;#f84547;#95c76f;#efa16b;#8485ce;#b74989;#64878f;#e8e8e8;#474160;#f84547;#95c76f;#efa16b;#8485ce;#b74989;#64878f;#f8f8f8
