# Scheme name: Tokyo City Light
# Scheme author: Michaël Ball
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-tokyo-city-light
ColorForeground=#343b59
ColorBackground=#fbfbfd
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#f6f6f8;#8c4351;#485e30;#4c505e;#34548a;#5a4a78;#4c505e;#1d252c;#edeff6;#8c4351;#485e30;#4c505e;#34548a;#5a4a78;#4c505e;#171d23
