# Scheme name: Oxocarbon Dark
# Scheme author: shaunsingh/IBM
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-oxocarbon-dark
ColorForeground=#f2f4f8
ColorBackground=#161616
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#262626;#3ddbd9;#33b1ff;#ee5396;#42be65;#be95ff;#ff7eb6;#ffffff;#393939;#3ddbd9;#33b1ff;#ee5396;#42be65;#be95ff;#ff7eb6;#08bdba
