# Scheme name: Atelier Estuary Light
# Scheme author: Bram de Haan (http://atelierbramdehaan.nl)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-atelier-estuary-light
ColorForeground=#5f5e4e
ColorBackground=#f4f3ec
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#e7e6df;#ba6236;#7d9726;#a5980d;#36a166;#5f9182;#5b9d48;#302f27;#929181;#ba6236;#7d9726;#a5980d;#36a166;#5f9182;#5b9d48;#22221b
