# Scheme name: Unikitty
# Scheme author: FredHappyface (https://github.com/fredHappyface)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base24-unikitty
ColorForeground=#b9b1b8
ColorBackground=#ff8cd9
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#0c0c0c;#a80f20;#bafc8b;#0074ea;#145fcd;#ff36a2;#6bd0bc;#e1d6e0;#424242;#d81329;#d2ffaf;#ffee50;#0074ea;#fdd5e5;#79ebd5;#fff2fd
