# Scheme name: OneDark Dark
# Scheme author: olimorris (https://github.com/olimorris)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-onedark-dark
ColorForeground=#abb2bf
ColorBackground=#000000
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1c1f24;#ef596f;#89ca78;#e5c07b;#61afef;#d55fde;#2bbac5;#b6bdca;#2c313a;#ef596f;#89ca78;#e5c07b;#61afef;#d55fde;#2bbac5;#c8ccd4
