# Scheme name: Black Metal (Marduk)
# Scheme author: metalelf0 (https://github.com/metalelf0)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-black-metal-marduk
ColorForeground=#c1c1c1
ColorBackground=#000000
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#121212;#5f8787;#a5aaa7;#626b67;#888888;#999999;#aaaaaa;#999999;#222222;#5f8787;#a5aaa7;#626b67;#888888;#999999;#aaaaaa;#c1c1c1
