# Scheme name: Terracotta
# Scheme author: Alexander Rossell Hayes (https://github.com/rossellhayes)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-terracotta
ColorForeground=#473731
ColorBackground=#efeae8
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#dfd6d1;#a75045;#7a894a;#ce943e;#625574;#8d5968;#847f9e;#352a25;#d0c1bb;#a75045;#7a894a;#ce943e;#625574;#8d5968;#847f9e;#241c19
