# Scheme name: One Black
# Scheme author: FredHappyface (https://github.com/fredHappyface)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base24-one-black
ColorForeground=#abb2bf
ColorBackground=#000000
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#000000;#e05561;#8cc265;#e6b965;#4aa5f0;#c162de;#42b3c2;#e6e6e6;#4f5666;#ff616e;#a5e075;#f0a45d;#4dc4ff;#de73ff;#4cd1e0;#ffffff
