# Scheme name: Icy Dark
# Scheme author: icyphox (https://icyphox.ga)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-icy
ColorForeground=#095b67
ColorBackground=#021012
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#031619;#16c1d9;#4dd0e1;#80deea;#00bcd4;#00acc1;#26c6da;#0c7c8c;#041f23;#16c1d9;#4dd0e1;#80deea;#00bcd4;#00acc1;#26c6da;#109cb0
