# Scheme name: Atelier Sulphurpool Light
# Scheme author: Bram de Haan (http://atelierbramdehaan.nl)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-atelier-sulphurpool-light
ColorForeground=#5e6687
ColorBackground=#f5f7ff
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#dfe2f1;#c94922;#ac9739;#c08b30;#3d8fd1;#6679cc;#22a2c9;#293256;#979db4;#c94922;#ac9739;#c08b30;#3d8fd1;#6679cc;#22a2c9;#202746
