# Scheme name: Piatto Light
# Scheme author: FredHappyface (https://github.com/fredHappyface)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base24-piatto-light
ColorForeground=#cfcfcf
ColorBackground=#ffffff
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#414141;#b23771;#66781e;#3c5ea8;#3c5ea8;#a454b2;#66781e;#ffffff;#3f3f3f;#db3365;#829429;#cd6f34;#3c5ea8;#a454b2;#829429;#f2f2f2
