# Scheme name: Atelier Cave Light
# Scheme author: Bram de Haan (http://atelierbramdehaan.nl)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-atelier-cave-light
ColorForeground=#585260
ColorBackground=#efecf4
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#e2dfe7;#be4678;#2a9292;#a06e3b;#576ddb;#955ae7;#398bc6;#26232a;#8b8792;#be4678;#2a9292;#a06e3b;#576ddb;#955ae7;#398bc6;#19171c
