# Scheme name: Brogrammer
# Scheme author: FredHappyface (https://github.com/fredHappyface)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base24-brogrammer
ColorForeground=#c1c8d7
ColorBackground=#131313
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1f1f1f;#f71118;#2cc55d;#0f80d5;#2a84d2;#4e59b7;#0f80d5;#e3e6ed;#2a3141;#de342e;#1dd260;#f2bd09;#509bdc;#524fb9;#289af0;#ffffff
