# Scheme name: Vibrant Ink
# Scheme author: FredHappyface (https://github.com/fredHappyface)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base24-vibrant-ink
ColorForeground=#cdcdcd
ColorBackground=#000000
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#878787;#ff6600;#ccff04;#0000ff;#44b3cc;#9933cc;#44b3cc;#f5f5f5;#555555;#ff0000;#00ff00;#ffff00;#0000ff;#ff00ff;#00ffff;#e5e5e5
