# Scheme name: Circus
# Scheme author: Stephan Boyer (https://github.com/stepchowfun) and Esther Wang (https://github.com/ewang12)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-circus
ColorForeground=#a7a7a7
ColorBackground=#191919
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#202020;#dc657d;#84b97c;#c3ba63;#639ee4;#b888e2;#4bb1a7;#808080;#303030;#dc657d;#84b97c;#c3ba63;#639ee4;#b888e2;#4bb1a7;#ffffff
