# Scheme name: Da One Ocean
# Scheme author: NNB (https://github.com/NNBnh)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-da-one-ocean
ColorForeground=#ffffff
ColorBackground=#171726
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#22273d;#fa7883;#98c379;#ff9470;#6bb8ff;#e799ff;#8af5ff;#ffffff;#525866;#fa7883;#98c379;#ff9470;#6bb8ff;#e799ff;#8af5ff;#ffffff
