# Scheme name: Twilight
# Scheme author: David Hart (https://github.com/hartbit)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-twilight
ColorForeground=#a7a7a7
ColorBackground=#1e1e1e
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#323537;#cf6a4c;#8f9d6a;#f9ee98;#7587a6;#9b859d;#afc4db;#c3c3c3;#464b50;#cf6a4c;#8f9d6a;#f9ee98;#7587a6;#9b859d;#afc4db;#ffffff
