# Scheme name: Chalkboard
# Scheme author: FredHappyface (https://github.com/fredHappyface)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base24-chalkboard
ColorForeground=#afafaf
ColorBackground=#29262f
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#000000;#c37372;#72c373;#aaaadb;#7372c3;#c372c2;#72c2c3;#d9d9d9;#323232;#dbaaaa;#aadbaa;#dadbaa;#aaaadb;#dbaada;#aadadb;#ffffff
