# Scheme name: Hardcore
# Scheme author: Chris Caller
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-hardcore
ColorForeground=#cdcdcd
ColorBackground=#212121
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#303030;#f92672;#a6e22e;#e6db74;#66d9ef;#9e6ffe;#708387;#e5e5e5;#353535;#f92672;#a6e22e;#e6db74;#66d9ef;#9e6ffe;#708387;#ffffff
