# Scheme name: Windows 10 Light
# Scheme author: Fergus Collins (https://github.com/ferguscollins)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-windows-10-light
ColorForeground=#767676
ColorBackground=#f2f2f2
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#e5e5e5;#c50f1f;#13a10e;#c19c00;#0037da;#881798;#3a96dd;#414141;#d9d9d9;#c50f1f;#13a10e;#c19c00;#0037da;#881798;#3a96dd;#0c0c0c
