# Scheme name: Measured Light
# Scheme author: Measured (https://measured.co)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-measured-light
ColorForeground=#292929
ColorBackground=#fdf9f5
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#f9f5f1;#ac1f35;#0c680c;#645a00;#0158ad;#6645c2;#01716f;#181818;#ffeada;#ac1f35;#0c680c;#645a00;#0158ad;#6645c2;#01716f;#000000
