# Scheme name: Ciapre
# Scheme author: FredHappyface (https://github.com/fredHappyface)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base24-ciapre
ColorForeground=#978f73
ColorBackground=#181c27
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#181818;#800009;#48513b;#2f97c6;#566d8c;#724c7c;#5b4f4a;#ada37e;#555555;#ab3834;#a6a65d;#dcde7b;#2f97c6;#d33060;#f3dab1;#f3f3f3
