# Scheme name: Everforest Dark Hard
# Scheme author: Sainnhe Park (https://github.com/sainnhe)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-everforest-dark-hard
ColorForeground=#d3c6aa
ColorBackground=#272e33
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#2e383c;#e67e80;#a7c080;#dbbc7f;#7fbbb3;#d699b6;#83c092;#edeada;#414b50;#e67e80;#a7c080;#dbbc7f;#7fbbb3;#d699b6;#83c092;#fffbef
