# Scheme name: Wryan
# Scheme author: FredHappyface (https://github.com/fredHappyface)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base24-wryan
ColorForeground=#768488
ColorBackground=#101010
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#333333;#8c4665;#287373;#477ab3;#395573;#5e468c;#31658c;#899ca1;#3d3d3d;#bf4d80;#53a6a6;#9e9ecb;#477ab3;#7e62b3;#6096bf;#c0c0c0
