# Scheme name: Equilibrium Dark
# Scheme author: Carlo Abelli
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-equilibrium-dark
ColorForeground=#afaba2
ColorBackground=#0c1118
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#181c22;#f04339;#7f8b00;#bb8801;#008dd1;#6a7fd2;#00948b;#cac6bd;#22262d;#f04339;#7f8b00;#bb8801;#008dd1;#6a7fd2;#00948b;#e7e2d9
