# Scheme name: Unikitty Light
# Scheme author: Josh W Lewis (@joshwlewis)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-unikitty-light
ColorForeground=#6c696e
ColorBackground=#ffffff
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#e1e1e2;#d8137f;#17ad98;#dc8a0e;#775dff;#aa17e6;#149bda;#4f4b51;#c4c3c5;#d8137f;#17ad98;#dc8a0e;#775dff;#aa17e6;#149bda;#322d34
