# Scheme name: Gruvbox Material Dark, Hard
# Scheme author: Mayush Kumar (https://github.com/MayushKumar), sainnhe (https://github.com/sainnhe/gruvbox-material-vscode)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-gruvbox-material-dark-hard
ColorForeground=#ddc7a1
ColorBackground=#202020
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#2a2827;#ea6962;#a9b665;#d8a657;#7daea3;#d3869b;#89b482;#ebdbb2;#504945;#ea6962;#a9b665;#d8a657;#7daea3;#d3869b;#89b482;#fbf1c7
