# Scheme name: standardized-dark
# Scheme author: ali (https://github.com/ali-githb/base16-standardized-scheme)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-standardized-dark
ColorForeground=#c0c0c0
ColorBackground=#222222
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#303030;#e15d67;#5db129;#e1b31a;#00a3f2;#b46ee0;#21c992;#e0e0e0;#555555;#e15d67;#5db129;#e1b31a;#00a3f2;#b46ee0;#21c992;#ffffff
