# Scheme name: Silk Light
# Scheme author: Gabriel Fontes (https://github.com/Misterio77)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-silk-light
ColorForeground=#385156
ColorBackground=#e9f1ef
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#ccd4d3;#cf432e;#6ca38c;#cfad25;#39aac9;#6e6582;#329ca2;#0e3c46;#90b7b6;#cf432e;#6ca38c;#cfad25;#39aac9;#6e6582;#329ca2;#d2faff
