#!/bin/sh

set -e

# Update help tags.
cd ~/.config/nvim/pack

PACKS=""
for PACK in $(find . -maxdepth 3 -type d -path '*/opt/*' | cut -f 4 -d /); do
  PACKS="${PACKS}packadd! $PACK | "
done

COMMANDS="packloadall | call pathogen#helptags() | quit"
echo "Running: nvim -u NONE -N -c \"${PACKS}${COMMANDS}\""
nvim -u NONE -N -c "${PACKS}${COMMANDS}"
