#!/bin/sh

set -e

# Conditionals here are to ensure we only do any work in submodules under
# aspects/vim/files/.config/.nvim/pack:

git submodule foreach '
  if [ "${path##aspects/vim/files/.config/nvim/pack/}" != "$path" ]; then
    NAME=$(basename $path)
    BRANCH=$(git config -f $toplevel/.gitmodules submodule."$NAME".branch || echo master)
    git remote update --prune
    git checkout $BRANCH
  fi
'

git submodule foreach '
  if [ "${path##aspects/vim/files/.config/nvim/pack/}" != "$path" ]; then
    git pull --recurse-submodules || :
  fi
'

git submodule foreach '
  if [ "${path##aspects/vim/files/.config/nvim/pack/}" != "$path" ]; then
    git submodule update --init --recursive || :
  fi
'
