#!/bin/sh

set -e

# Update help tags.
cd ~/.config/nvim/pack

COMMANDS=""
for PACK in $(find . -maxdepth 3 -type d -path '*/opt/*' | cut -f 4 -d /); do
  COMMANDS="${COMMANDS}packadd! $PACK | "
done

COMMANDS="${COMMANDS}packloadall | "
COMMANDS="${COMMANDS}call pathogen#helptags() | "
COMMANDS="${COMMANDS}quit"

# Using 'verbose' level 1, the minimum required to get Neovim to print Ex
# commands that it is running.
echo "$COMMANDS" | nvim -i NONE -u NONE -V1 -es
