" add .vim/bundle subdirs to runtime path
runtime bundle/pathogen/autoload/pathogen.vim
call pathogen#infect()

" extension -> filetype mappings
let filetype_m='objc'
let filetype_pl='prolog'

" automatic, language-dependent indentation, syntax coloring and other
" functionality
filetype indent plugin on
syntax on

source $VIMRUNTIME/macros/matchit.vim

" prevent tcomment from making a zillion mappings (we just want the operator)
let g:tcommentMapLeader1=''
let g:tcommentMapLeader2=''
let g:tcommentMapLeaderCommentAnyway=''
let g:tcommentTextObjectInlineComment=''
" the default (g<) is a bit awkward to type
let g:tcommentMapLeaderUncommentAnyway='gu'

" allow for per-host overrides; usually stored in ~/.vim/vimrc.local
runtime vimrc.local

" After this file is sourced, plug-in code will be evaluated.
" See ~/.vim/after for files evaluated after that.
" See `:scriptnames` for a list of all scripts, in evaluation order.
" Launch Vim with `vim --startuptime vim.log` for profiling info.
"
" To see all leader mappings currently in use:
"
"   grep -R leader .vim/vimrc .vim/plugin | perl -pe 's/.+(<leader>\w+).+/\1/' | sort | uniq
