#!/bin/bash

#
# https://support.1password.com/command-line-getting-started/
#
# Full docs: https://support.1password.com/command-line/
#
# gpg --receive-keys 3FEF9748469ADBE15DA7CA80AC2D62742012EA22
# gpg --verify op.sig op
#
# First sign-in:
#
# op signin vault.1password.com $USER@example.net $SECRET_KEY
#
# Subsequent sign-ins:
#
# op signin vault
#
# Exporting to shell:
#
# eval $(op signin vault)
#

set -e

# https://stackoverflow.com/a/246128/2103996
BASE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$BASE"
echo 'Running from:'
pwd

echo 'Using 1Password command-line tool:'
which op

echo 'Using jq JSON tool:'
which jq

echo 'Using parallel:'
which parallel

FOLDER=$(date '+%Y-%m-%d')
mkdir -p "$FOLDER"
cd "$FOLDER"
echo 'Dumping to:'
pwd

eval $(op signin vault)

echo '-> vaults.json'
op list vaults | jq . > vaults.json

while read VAULT <&3
do
  echo "-> vaults/$VAULT/items/"
  echo "-> vaults/$VAULT/documents/"
  mkdir -p vaults/"$VAULT"/{items,documents}

  echo "-> vaults/$VAULT/vault.json"
  op get vault "$VAULT" | jq . > vaults/"$VAULT"/vault.json

  echo "-> vaults/$VAULT/items.json"
  op list items --include-trash --vault="$VAULT" | jq . > vaults/"$VAULT"/items.json

  echo "-> vaults/$VAULT/documents.json"
  op list documents --vault="$VAULT" | jq . > vaults/"$VAULT"/documents.json

  jq -r '.[].uuid' vaults/"$VAULT"/items.json | parallel --verbose --retries 5 --eta -j 4 "op get item '{}' | jq . > 'vaults/$VAULT/items/{}.json'"

  # Many of these fail with 500 errors.
  jq -r '.[].uuid' vaults/"$VAULT"/documents.json | parallel --verbose --retries 5 --eta -j 1 "op get document '{}' > 'vaults/$VAULT/documents/{}.bin'"

  # while read DOCUMENT <&4
  # do
  #   echo "Document: $DOCUMENT"
  #   op get document "$DOCUMENT" > vaults/"$VAULT"/documents/"$DOCUMENT".bin || \
  #     echo 'Retrieval failed!'
  # done 4< <(jq -r '.[].uuid' vaults/"$VAULT"/documents.json)
done 3< <(jq -r '.[].uuid' vaults.json)
