local augroup = wincent.vim.augroup

augroup('WincentAutocmds', function(autocmd)
  autocmd('BufEnter', '*', wincent.autocmds.buf_enter)
  autocmd('BufLeave', '?*', wincent.autocmds.buf_leave)
  autocmd('BufWinEnter', '?*', wincent.autocmds.buf_win_enter)
  autocmd('BufWritePost', '*/spell/*.add', 'silent! :mkspell! %')
  autocmd('BufWritePost', '?*', wincent.autocmds.buf_write_post)
  autocmd('CmdlineChanged', '*', wincent.autocmds.cmdline_changed)
  autocmd('FocusGained', '*', wincent.autocmds.focus_gained)
  autocmd('FocusLost', '*', wincent.autocmds.focus_lost)
  autocmd('InsertEnter', '*', wincent.autocmds.insert_enter)
  autocmd('InsertLeave', '*', wincent.autocmds.insert_leave)
  autocmd('InsertLeave', '*', 'set nopaste')
  autocmd('TextYankPost', '*', wincent.autocmds.text_yank_post)
  autocmd('VimEnter', '*', wincent.autocmds.vim_enter)
  autocmd('VimResized', '*', 'execute "normal! \\<c-w>="')
  autocmd('WinEnter', '*', wincent.autocmds.win_enter)
  autocmd('WinLeave', '*', wincent.autocmds.win_leave)
end)
