local augroup = wincent.vim.augroup
local autocmd = wincent.vim.autocmd

augroup('WincentAutocmds', function ()
  autocmd('BufEnter', '*', wincent.autocmds.buf_enter)
  autocmd('BufFilePost,BufNewFile,BufReadPost', '*', 'call wincent#autocmds#apply_overrides()')
  autocmd('BufLeave', '?*', wincent.autocmds.buf_leave)
  autocmd('BufWinEnter', '?*', wincent.autocmds.buf_win_enter)
  autocmd('BufWritePost', '*/spell/*.add', 'silent! :mkspell! %')
  autocmd('BufWritePost', '?*', wincent.autocmds.buf_write_post)
  autocmd('FocusGained', '*', wincent.autocmds.focus_gained)
  autocmd('FocusLost', '*', wincent.autocmds.focus_lost)
  autocmd('InsertEnter', '*', wincent.autocmds.insert_enter)
  autocmd('InsertLeave', '*', wincent.autocmds.insert_leave)
  autocmd('InsertLeave', '*', 'set nopaste')
  autocmd('TextYankPost', '*', "silent! lua vim.highlight.on_yank {higroup='Substitute', on_visual=false, timeout=200}")
  autocmd('VimEnter', '*', wincent.autocmds.vim_enter)
  autocmd('VimResized', '*', 'execute "normal! \\<c-w>="')
  autocmd('WinEnter', '*', wincent.autocmds.win_enter)
  autocmd('WinLeave', '*', wincent.autocmds.win_leave)
end)
