local augroup = require('wincent.nvim.augroup')
local autocmds = require('wincent.autocmds')

augroup('wincent.autocmds', function(autocmd)
  autocmd('BufEnter', '*', autocmds.buf_enter)
  autocmd('BufLeave', '?*', autocmds.buf_leave)
  autocmd('BufWinEnter', '?*', autocmds.buf_win_enter)
  autocmd('BufWritePost', '*/spell/*.add', 'silent! :mkspell! %')
  autocmd('BufWritePost', '?*', autocmds.buf_write_post)
  autocmd('CmdlineChanged', '*', autocmds.cmdline_changed)
  autocmd('FocusGained', '*', autocmds.focus_gained)
  autocmd('FocusLost', '*', autocmds.focus_lost)
  autocmd('InsertEnter', '*', autocmds.insert_enter)
  autocmd('InsertLeave', '*', autocmds.insert_leave)
  autocmd('InsertLeave', '*', 'set nopaste')
  autocmd('TextYankPost', '*', autocmds.text_yank_post)
  autocmd('VimEnter', '*', autocmds.vim_enter)
  autocmd('VimResized', '*', 'wincmd =')
  autocmd('WinEnter', '*', autocmds.win_enter)
  autocmd('WinLeave', '*', autocmds.win_leave)
end)
