# Base24 Arroz con Dulce Dark
# Scheme author: Richard Martinez
# Template author: Tinted Theming: (https://github.com/tinted-theming)

# default statusbar colors
set-option -g status-style "fg=#C8A77A,bg=#2C1A13"

# default window title colors
set-window-option -g window-status-style "fg=#C8A77A,bg=#2C1A13"

# active window title colors
set-window-option -g window-status-current-style "fg=#D9A441,bg=#2C1A13"

# pane border
set-option -g pane-border-style "fg=#2C1A13"
set-option -g pane-active-border-style "fg=#C8A77A"

# message text
set-option -g message-style "fg=#F8EBD3,bg=#3B241A"

# pane number display
set-option -g display-panes-active-colour "#C8A77A"
set-option -g display-panes-colour "#2C1A13"

# clock
set-window-option -g clock-mode-colour "#B99AC8"

# copy mode highlight
set-window-option -g mode-style "fg=#C8A77A,bg=#3B241A"

# bell
set-window-option -g window-status-bell-style "fg=#21140F,bg=#E07A8A"

# style for window titles with activity
set-window-option -g window-status-activity-style "fg=#F2DFC0,bg=#2C1A13"

# style for command messages
set-option -g message-command-style "fg=#F8EBD3,bg=#3B241A"

# Optional active/inactive pane state
if-shell '[ "$TINTED_TMUX_OPTION_ACTIVE" = "1" ]' {
  set-window-option -g window-active-style "fg=#F2DFC0,bg=#21140F"
  set-window-option -g window-style "fg=#F2DFC0,bg=#2C1A13"
}

# Optional statusbar
if-shell '[ "$TINTED_TMUX_OPTION_STATUSBAR" = "1" ]' {
  set-option -g status "on"
  set-option -g status-justify "left"
  set-option -g status-left "#[fg=#F2DFC0,bg=#A98568] #S #[fg=#A98568,bg=#2C1A13,nobold,noitalics,nounderscore]"
  set-option -g status-left-length "80"
  set-option -g status-left-style none
  set-option -g status-right "#[fg=#3B241A,bg=#2C1A13 nobold, nounderscore, noitalics]#[fg=#C8A77A,bg=#3B241A] %Y-%m-%d  %H:%M #[fg=#F2DFC0,bg=#3B241A,nobold,noitalics,nounderscore]#[fg=#2C1A13,bg=#F2DFC0] #h "
  set-option -g status-right-length "80"
  set-option -g status-right-style none
  set-window-option -g window-status-current-format "#[fg=#2C1A13,bg=#D9A441,nobold,noitalics,nounderscore]#[fg=#3B241A,bg=#D9A441] #I #[fg=#3B241A,bg=#D9A441,bold] #W#{?window_zoomed_flag,*Z,}} #[fg=#D9A441,bg=#2C1A13,nobold,noitalics,nounderscore]"
  set-window-option -g window-status-format "#[fg=#2C1A13,bg=#3B241A,noitalics]#[fg=#F8EBD3,bg=#3B241A] #I #[fg=#F8EBD3,bg=#3B241A] #W#{?window_zoomed_flag,*Z,}} #[fg=#3B241A,bg=#2C1A13,noitalics]"
  set-window-option -g window-status-separator ""
}

# vim: set ft=tmux tw=0:
