# Base24 Brasa
# Scheme author: Teshre
# Template author: Tinted Theming: (https://github.com/tinted-theming)

# default statusbar colors
set-option -g status-style "fg=#B59D88,bg=#2B1C14"

# default window title colors
set-window-option -g window-status-style "fg=#B59D88,bg=#2B1C14"

# active window title colors
set-window-option -g window-status-current-style "fg=#F0B23A,bg=#2B1C14"

# pane border
set-option -g pane-border-style "fg=#2B1C14"
set-option -g pane-active-border-style "fg=#B59D88"

# message text
set-option -g message-style "fg=#F6E1CC,bg=#45261A"

# pane number display
set-option -g display-panes-active-colour "#B59D88"
set-option -g display-panes-colour "#2B1C14"

# clock
set-window-option -g clock-mode-colour "#9AA6E0"

# copy mode highlight
set-window-option -g mode-style "fg=#B59D88,bg=#45261A"

# bell
set-window-option -g window-status-bell-style "fg=#1A0F0A,bg=#F2685A"

# style for window titles with activity
set-window-option -g window-status-activity-style "fg=#F0D8C0,bg=#2B1C14"

# style for command messages
set-option -g message-command-style "fg=#F6E1CC,bg=#45261A"

# Optional active/inactive pane state
if-shell '[ "$TINTED_TMUX_OPTION_ACTIVE" = "1" ]' {
  set-window-option -g window-active-style "fg=#F0D8C0,bg=#1A0F0A"
  set-window-option -g window-style "fg=#F0D8C0,bg=#2B1C14"
}

# Optional statusbar
if-shell '[ "$TINTED_TMUX_OPTION_STATUSBAR" = "1" ]' {
  set-option -g status "on"
  set-option -g status-justify "left"
  set-option -g status-left "#[fg=#F0D8C0,bg=#7A6150] #S #[fg=#7A6150,bg=#2B1C14,nobold,noitalics,nounderscore]"
  set-option -g status-left-length "80"
  set-option -g status-left-style none
  set-option -g status-right "#[fg=#45261A,bg=#2B1C14 nobold, nounderscore, noitalics]#[fg=#B59D88,bg=#45261A] %Y-%m-%d  %H:%M #[fg=#F0D8C0,bg=#45261A,nobold,noitalics,nounderscore]#[fg=#2B1C14,bg=#F0D8C0] #h "
  set-option -g status-right-length "80"
  set-option -g status-right-style none
  set-window-option -g window-status-current-format "#[fg=#2B1C14,bg=#F0B23A,nobold,noitalics,nounderscore]#[fg=#45261A,bg=#F0B23A] #I #[fg=#45261A,bg=#F0B23A,bold] #W#{?window_zoomed_flag,*Z,}} #[fg=#F0B23A,bg=#2B1C14,nobold,noitalics,nounderscore]"
  set-window-option -g window-status-format "#[fg=#2B1C14,bg=#45261A,noitalics]#[fg=#F6E1CC,bg=#45261A] #I #[fg=#F6E1CC,bg=#45261A] #W#{?window_zoomed_flag,*Z,}} #[fg=#45261A,bg=#2B1C14,noitalics]"
  set-window-option -g window-status-separator ""
}

# vim: set ft=tmux tw=0:
