# Base24 Kissa Macchiato
# Scheme author: rwendell (https://github.com/rwendell/kissa)
# Template author: Tinted Theming: (https://github.com/tinted-theming)

# default statusbar colors
set-option -g status-style "fg=#D4C4A8,bg=#35322D"

# default window title colors
set-window-option -g window-status-style "fg=#D4C4A8,bg=#35322D"

# active window title colors
set-window-option -g window-status-current-style "fg=#EAC67A,bg=#35322D"

# pane border
set-option -g pane-border-style "fg=#35322D"
set-option -g pane-active-border-style "fg=#D4C4A8"

# message text
set-option -g message-style "fg=#E8D5B7,bg=#47443F"

# pane number display
set-option -g display-panes-active-colour "#D4C4A8"
set-option -g display-panes-colour "#35322D"

# clock
set-window-option -g clock-mode-colour "#7FA8D4"

# copy mode highlight
set-window-option -g mode-style "fg=#D4C4A8,bg=#47443F"

# bell
set-window-option -g window-status-bell-style "fg=#1F1C16,bg=#E87777"

# style for window titles with activity
set-window-option -g window-status-activity-style "fg=#FAF0E6,bg=#35322D"

# style for command messages
set-option -g message-command-style "fg=#E8D5B7,bg=#47443F"

# Optional active/inactive pane state
if-shell '[ "$TINTED_TMUX_OPTION_ACTIVE" = "1" ]' {
  set-window-option -g window-active-style "fg=#FAF0E6,bg=#1F1C16"
  set-window-option -g window-style "fg=#FAF0E6,bg=#35322D"
}

# Optional statusbar
if-shell '[ "$TINTED_TMUX_OPTION_STATUSBAR" = "1" ]' {
  set-option -g status "on"
  set-option -g status-justify "left"
  set-option -g status-left "#[fg=#FAF0E6,bg=#B8A48C] #S #[fg=#B8A48C,bg=#35322D,nobold,noitalics,nounderscore]"
  set-option -g status-left-length "80"
  set-option -g status-left-style none
  set-option -g status-right "#[fg=#47443F,bg=#35322D nobold, nounderscore, noitalics]#[fg=#D4C4A8,bg=#47443F] %Y-%m-%d  %H:%M #[fg=#FAF0E6,bg=#47443F,nobold,noitalics,nounderscore]#[fg=#35322D,bg=#FAF0E6] #h "
  set-option -g status-right-length "80"
  set-option -g status-right-style none
  set-window-option -g window-status-current-format "#[fg=#35322D,bg=#EAC67A,nobold,noitalics,nounderscore]#[fg=#47443F,bg=#EAC67A] #I #[fg=#47443F,bg=#EAC67A,bold] #W#{?window_zoomed_flag,*Z,}} #[fg=#EAC67A,bg=#35322D,nobold,noitalics,nounderscore]"
  set-window-option -g window-status-format "#[fg=#35322D,bg=#47443F,noitalics]#[fg=#E8D5B7,bg=#47443F] #I #[fg=#E8D5B7,bg=#47443F] #W#{?window_zoomed_flag,*Z,}} #[fg=#47443F,bg=#35322D,noitalics]"
  set-window-option -g window-status-separator ""
}

# vim: set ft=tmux tw=0:
