# Base24 Lichen Chartreuse Dark
# Scheme author: Aaron Colichia (https://aaron.colichia.org/)
# Template author: Tinted Theming: (https://github.com/tinted-theming)

# default statusbar colors
set-option -g status-style "fg=#a0a598,bg=#1c1e1a"

# default window title colors
set-window-option -g window-status-style "fg=#a0a598,bg=#1c1e1a"

# active window title colors
set-window-option -g window-status-current-style "fg=#d5ad73,bg=#1c1e1a"

# pane border
set-option -g pane-border-style "fg=#1c1e1a"
set-option -g pane-active-border-style "fg=#a0a598"

# message text
set-option -g message-style "fg=#ecefe7,bg=#3e5123"

# pane number display
set-option -g display-panes-active-colour "#a0a598"
set-option -g display-panes-colour "#1c1e1a"

# clock
set-window-option -g clock-mode-colour "#78adc4"

# copy mode highlight
set-window-option -g mode-style "fg=#a0a598,bg=#3e5123"

# bell
set-window-option -g window-status-bell-style "fg=#151613,bg=#e28b82"

# style for window titles with activity
set-window-option -g window-status-activity-style "fg=#e0e5da,bg=#1c1e1a"

# style for command messages
set-option -g message-command-style "fg=#ecefe7,bg=#3e5123"

# Optional active/inactive pane state
if-shell '[ "$TINTED_TMUX_OPTION_ACTIVE" = "1" ]' {
  set-window-option -g window-active-style "fg=#e0e5da,bg=#151613"
  set-window-option -g window-style "fg=#e0e5da,bg=#1c1e1a"
}

# Optional statusbar
if-shell '[ "$TINTED_TMUX_OPTION_STATUSBAR" = "1" ]' {
  set-option -g status "on"
  set-option -g status-justify "left"
  set-option -g status-left "#[fg=#e0e5da,bg=#899282] #S #[fg=#899282,bg=#1c1e1a,nobold,noitalics,nounderscore]"
  set-option -g status-left-length "80"
  set-option -g status-left-style none
  set-option -g status-right "#[fg=#3e5123,bg=#1c1e1a nobold, nounderscore, noitalics]#[fg=#a0a598,bg=#3e5123] %Y-%m-%d  %H:%M #[fg=#e0e5da,bg=#3e5123,nobold,noitalics,nounderscore]#[fg=#1c1e1a,bg=#e0e5da] #h "
  set-option -g status-right-length "80"
  set-option -g status-right-style none
  set-window-option -g window-status-current-format "#[fg=#1c1e1a,bg=#b2d084,nobold,noitalics,nounderscore]#[fg=#3e5123,bg=#b2d084] #I #[fg=#3e5123,bg=#b2d084,bold] #W#{?window_zoomed_flag,*Z,}} #[fg=#b2d084,bg=#1c1e1a,nobold,noitalics,nounderscore]"
  set-window-option -g window-status-format "#[fg=#1c1e1a,bg=#3e5123,noitalics]#[fg=#ecefe7,bg=#3e5123] #I #[fg=#ecefe7,bg=#3e5123] #W#{?window_zoomed_flag,*Z,}} #[fg=#3e5123,bg=#1c1e1a,noitalics]"
  set-window-option -g window-status-separator ""
}

# vim: set ft=tmux tw=0:
