# Base24 Mezcal
# Scheme author: Teshre
# Template author: Tinted Theming: (https://github.com/tinted-theming)

# default statusbar colors
set-option -g status-style "fg=#A79E8C,bg=#221F14"

# default window title colors
set-window-option -g window-status-style "fg=#A79E8C,bg=#221F14"

# active window title colors
set-window-option -g window-status-current-style "fg=#D9A441,bg=#221F14"

# pane border
set-option -g pane-border-style "fg=#221F14"
set-option -g pane-active-border-style "fg=#A79E8C"

# message text
set-option -g message-style "fg=#E9E1CF,bg=#36301E"

# pane number display
set-option -g display-panes-active-colour "#A79E8C"
set-option -g display-panes-colour "#221F14"

# clock
set-window-option -g clock-mode-colour "#8AA6C0"

# copy mode highlight
set-window-option -g mode-style "fg=#A79E8C,bg=#36301E"

# bell
set-window-option -g window-status-bell-style "fg=#13110E,bg=#DA6E54"

# style for window titles with activity
set-window-option -g window-status-activity-style "fg=#E0D8C8,bg=#221F14"

# style for command messages
set-option -g message-command-style "fg=#E9E1CF,bg=#36301E"

# Optional active/inactive pane state
if-shell '[ "$TINTED_TMUX_OPTION_ACTIVE" = "1" ]' {
  set-window-option -g window-active-style "fg=#E0D8C8,bg=#13110E"
  set-window-option -g window-style "fg=#E0D8C8,bg=#221F14"
}

# Optional statusbar
if-shell '[ "$TINTED_TMUX_OPTION_STATUSBAR" = "1" ]' {
  set-option -g status "on"
  set-option -g status-justify "left"
  set-option -g status-left "#[fg=#E0D8C8,bg=#6E6450] #S #[fg=#6E6450,bg=#221F14,nobold,noitalics,nounderscore]"
  set-option -g status-left-length "80"
  set-option -g status-left-style none
  set-option -g status-right "#[fg=#36301E,bg=#221F14 nobold, nounderscore, noitalics]#[fg=#A79E8C,bg=#36301E] %Y-%m-%d  %H:%M #[fg=#E0D8C8,bg=#36301E,nobold,noitalics,nounderscore]#[fg=#221F14,bg=#E0D8C8] #h "
  set-option -g status-right-length "80"
  set-option -g status-right-style none
  set-window-option -g window-status-current-format "#[fg=#221F14,bg=#D9A441,nobold,noitalics,nounderscore]#[fg=#36301E,bg=#D9A441] #I #[fg=#36301E,bg=#D9A441,bold] #W#{?window_zoomed_flag,*Z,}} #[fg=#D9A441,bg=#221F14,nobold,noitalics,nounderscore]"
  set-window-option -g window-status-format "#[fg=#221F14,bg=#36301E,noitalics]#[fg=#E9E1CF,bg=#36301E] #I #[fg=#E9E1CF,bg=#36301E] #W#{?window_zoomed_flag,*Z,}} #[fg=#36301E,bg=#221F14,noitalics]"
  set-window-option -g window-status-separator ""
}

# vim: set ft=tmux tw=0:
