# Base24 Ocote
# Scheme author: Teshre
# Template author: Tinted Theming: (https://github.com/tinted-theming)

# default statusbar colors
set-option -g status-style "fg=#A99F8D,bg=#211B13"

# default window title colors
set-window-option -g window-status-style "fg=#A99F8D,bg=#211B13"

# active window title colors
set-window-option -g window-status-current-style "fg=#E8B43A,bg=#211B13"

# pane border
set-option -g pane-border-style "fg=#211B13"
set-option -g pane-active-border-style "fg=#A99F8D"

# message text
set-option -g message-style "fg=#F1E9D9,bg=#3A2E1C"

# pane number display
set-option -g display-panes-active-colour "#A99F8D"
set-option -g display-panes-colour "#211B13"

# clock
set-window-option -g clock-mode-colour "#82A6E0"

# copy mode highlight
set-window-option -g mode-style "fg=#A99F8D,bg=#3A2E1C"

# bell
set-window-option -g window-status-bell-style "fg=#14100C,bg=#E8635A"

# style for window titles with activity
set-window-option -g window-status-activity-style "fg=#E7DCC6,bg=#211B13"

# style for command messages
set-option -g message-command-style "fg=#F1E9D9,bg=#3A2E1C"

# Optional active/inactive pane state
if-shell '[ "$TINTED_TMUX_OPTION_ACTIVE" = "1" ]' {
  set-window-option -g window-active-style "fg=#E7DCC6,bg=#14100C"
  set-window-option -g window-style "fg=#E7DCC6,bg=#211B13"
}

# Optional statusbar
if-shell '[ "$TINTED_TMUX_OPTION_STATUSBAR" = "1" ]' {
  set-option -g status "on"
  set-option -g status-justify "left"
  set-option -g status-left "#[fg=#E7DCC6,bg=#6B6253] #S #[fg=#6B6253,bg=#211B13,nobold,noitalics,nounderscore]"
  set-option -g status-left-length "80"
  set-option -g status-left-style none
  set-option -g status-right "#[fg=#3A2E1C,bg=#211B13 nobold, nounderscore, noitalics]#[fg=#A99F8D,bg=#3A2E1C] %Y-%m-%d  %H:%M #[fg=#E7DCC6,bg=#3A2E1C,nobold,noitalics,nounderscore]#[fg=#211B13,bg=#E7DCC6] #h "
  set-option -g status-right-length "80"
  set-option -g status-right-style none
  set-window-option -g window-status-current-format "#[fg=#211B13,bg=#E8B43A,nobold,noitalics,nounderscore]#[fg=#3A2E1C,bg=#E8B43A] #I #[fg=#3A2E1C,bg=#E8B43A,bold] #W#{?window_zoomed_flag,*Z,}} #[fg=#E8B43A,bg=#211B13,nobold,noitalics,nounderscore]"
  set-window-option -g window-status-format "#[fg=#211B13,bg=#3A2E1C,noitalics]#[fg=#F1E9D9,bg=#3A2E1C] #I #[fg=#F1E9D9,bg=#3A2E1C] #W#{?window_zoomed_flag,*Z,}} #[fg=#3A2E1C,bg=#211B13,noitalics]"
  set-window-option -g window-status-separator ""
}

# vim: set ft=tmux tw=0:
