# Base24 Swamp Light
# Scheme author: Masroof Maindak (https://github.com/masroof-maindak)
# Template author: Tinted Theming: (https://github.com/tinted-theming)

# default statusbar colors
set-option -g status-style "fg=#A0907D,bg=#DDCEBC"

# default window title colors
set-window-option -g window-status-style "fg=#A0907D,bg=#DDCEBC"

# active window title colors
set-window-option -g window-status-current-style "fg=#993333,bg=#DDCEBC"

# pane border
set-option -g pane-border-style "fg=#DDCEBC"
set-option -g pane-active-border-style "fg=#A0907D"

# message text
set-option -g message-style "fg=#786653,bg=#C9B9A7"

# pane number display
set-option -g display-panes-active-colour "#A0907D"
set-option -g display-panes-colour "#DDCEBC"

# clock
set-window-option -g clock-mode-colour "#BF7979"

# copy mode highlight
set-window-option -g mode-style "fg=#A0907D,bg=#C9B9A7"

# bell
set-window-option -g window-status-bell-style "fg=#F1E3D1,bg=#D09700"

# style for window titles with activity
set-window-option -g window-status-activity-style "fg=#64513E,bg=#DDCEBC"

# style for command messages
set-option -g message-command-style "fg=#786653,bg=#C9B9A7"

# Optional active/inactive pane state
if-shell '[ "$TINTED_TMUX_OPTION_ACTIVE" = "1" ]' {
  set-window-option -g window-active-style "fg=#64513E,bg=#F1E3D1"
  set-window-option -g window-style "fg=#64513E,bg=#DDCEBC"
}

# Optional statusbar
if-shell '[ "$TINTED_TMUX_OPTION_STATUSBAR" = "1" ]' {
  set-option -g status "on"
  set-option -g status-justify "left"
  set-option -g status-left "#[fg=#64513E,bg=#B5A492] #S #[fg=#B5A492,bg=#DDCEBC,nobold,noitalics,nounderscore]"
  set-option -g status-left-length "80"
  set-option -g status-left-style none
  set-option -g status-right "#[fg=#C9B9A7,bg=#DDCEBC nobold, nounderscore, noitalics]#[fg=#A0907D,bg=#C9B9A7] %Y-%m-%d  %H:%M #[fg=#64513E,bg=#C9B9A7,nobold,noitalics,nounderscore]#[fg=#DDCEBC,bg=#64513E] #h "
  set-option -g status-right-length "80"
  set-option -g status-right-style none
  set-window-option -g window-status-current-format "#[fg=#DDCEBC,bg=#993333,nobold,noitalics,nounderscore]#[fg=#C9B9A7,bg=#993333] #I #[fg=#C9B9A7,bg=#993333,bold] #W#{?window_zoomed_flag,*Z,}} #[fg=#993333,bg=#DDCEBC,nobold,noitalics,nounderscore]"
  set-window-option -g window-status-format "#[fg=#DDCEBC,bg=#C9B9A7,noitalics]#[fg=#786653,bg=#C9B9A7] #I #[fg=#786653,bg=#C9B9A7] #W#{?window_zoomed_flag,*Z,}} #[fg=#C9B9A7,bg=#DDCEBC,noitalics]"
  set-window-option -g window-status-separator ""
}

# vim: set ft=tmux tw=0:
