# Base24 Swamp Dark
# Scheme author: Masroof Maindak (https://github.com/masroof-maindak)
# Template author: Tinted Theming: (https://github.com/tinted-theming)

# default statusbar colors
set-option -g status-style "fg=#B8A58C,bg=#3A3124"

# default window title colors
set-window-option -g window-status-style "fg=#B8A58C,bg=#3A3124"

# active window title colors
set-window-option -g window-status-current-style "fg=#A82D56,bg=#3A3124"

# pane border
set-option -g pane-border-style "fg=#3A3124"
set-option -g pane-active-border-style "fg=#B8A58C"

# message text
set-option -g message-style "fg=#EBE0BB,bg=#4D3F32"

# pane number display
set-option -g display-panes-active-colour "#B8A58C"
set-option -g display-panes-colour "#3A3124"

# clock
set-window-option -g clock-mode-colour "#C1666B"

# copy mode highlight
set-window-option -g mode-style "fg=#B8A58C,bg=#4D3F32"

# bell
set-window-option -g window-status-bell-style "fg=#242015,bg=#DB930D"

# style for window titles with activity
set-window-option -g window-status-activity-style "fg=#D2C3A4,bg=#3A3124"

# style for command messages
set-option -g message-command-style "fg=#EBE0BB,bg=#4D3F32"

# Optional active/inactive pane state
if-shell '[ "$TINTED_TMUX_OPTION_ACTIVE" = "1" ]' {
  set-window-option -g window-active-style "fg=#D2C3A4,bg=#242015"
  set-window-option -g window-style "fg=#D2C3A4,bg=#3A3124"
}

# Optional statusbar
if-shell '[ "$TINTED_TMUX_OPTION_STATUSBAR" = "1" ]' {
  set-option -g status "on"
  set-option -g status-justify "left"
  set-option -g status-left "#[fg=#D2C3A4,bg=#5F4E41] #S #[fg=#5F4E41,bg=#3A3124,nobold,noitalics,nounderscore]"
  set-option -g status-left-length "80"
  set-option -g status-left-style none
  set-option -g status-right "#[fg=#4D3F32,bg=#3A3124 nobold, nounderscore, noitalics]#[fg=#B8A58C,bg=#4D3F32] %Y-%m-%d  %H:%M #[fg=#D2C3A4,bg=#4D3F32,nobold,noitalics,nounderscore]#[fg=#3A3124,bg=#D2C3A4] #h "
  set-option -g status-right-length "80"
  set-option -g status-right-style none
  set-window-option -g window-status-current-format "#[fg=#3A3124,bg=#A82D56,nobold,noitalics,nounderscore]#[fg=#4D3F32,bg=#A82D56] #I #[fg=#4D3F32,bg=#A82D56,bold] #W#{?window_zoomed_flag,*Z,}} #[fg=#A82D56,bg=#3A3124,nobold,noitalics,nounderscore]"
  set-window-option -g window-status-format "#[fg=#3A3124,bg=#4D3F32,noitalics]#[fg=#EBE0BB,bg=#4D3F32] #I #[fg=#EBE0BB,bg=#4D3F32] #W#{?window_zoomed_flag,*Z,}} #[fg=#4D3F32,bg=#3A3124,noitalics]"
  set-window-option -g window-status-separator ""
}

# vim: set ft=tmux tw=0:
