# Base24 Tinta
# Scheme author: Teshre
# Template author: Tinted Theming: (https://github.com/tinted-theming)

# default statusbar colors
set-option -g status-style "fg=#9D9C9D,bg=#202023"

# default window title colors
set-window-option -g window-status-style "fg=#9D9C9D,bg=#202023"

# active window title colors
set-window-option -g window-status-current-style "fg=#C8B86A,bg=#202023"

# pane border
set-option -g pane-border-style "fg=#202023"
set-option -g pane-active-border-style "fg=#9D9C9D"

# message text
set-option -g message-style "fg=#E3E1DB,bg=#2C2C30"

# pane number display
set-option -g display-panes-active-colour "#9D9C9D"
set-option -g display-panes-colour "#202023"

# clock
set-window-option -g clock-mode-colour "#8A9AB0"

# copy mode highlight
set-window-option -g mode-style "fg=#9D9C9D,bg=#2C2C30"

# bell
set-window-option -g window-status-bell-style "fg=#101012,bg=#D0726A"

# style for window titles with activity
set-window-option -g window-status-activity-style "fg=#D8D6D0,bg=#202023"

# style for command messages
set-option -g message-command-style "fg=#E3E1DB,bg=#2C2C30"

# Optional active/inactive pane state
if-shell '[ "$TINTED_TMUX_OPTION_ACTIVE" = "1" ]' {
  set-window-option -g window-active-style "fg=#D8D6D0,bg=#101012"
  set-window-option -g window-style "fg=#D8D6D0,bg=#202023"
}

# Optional statusbar
if-shell '[ "$TINTED_TMUX_OPTION_STATUSBAR" = "1" ]' {
  set-option -g status "on"
  set-option -g status-justify "left"
  set-option -g status-left "#[fg=#D8D6D0,bg=#62626A] #S #[fg=#62626A,bg=#202023,nobold,noitalics,nounderscore]"
  set-option -g status-left-length "80"
  set-option -g status-left-style none
  set-option -g status-right "#[fg=#2C2C30,bg=#202023 nobold, nounderscore, noitalics]#[fg=#9D9C9D,bg=#2C2C30] %Y-%m-%d  %H:%M #[fg=#D8D6D0,bg=#2C2C30,nobold,noitalics,nounderscore]#[fg=#202023,bg=#D8D6D0] #h "
  set-option -g status-right-length "80"
  set-option -g status-right-style none
  set-window-option -g window-status-current-format "#[fg=#202023,bg=#C8B86A,nobold,noitalics,nounderscore]#[fg=#2C2C30,bg=#C8B86A] #I #[fg=#2C2C30,bg=#C8B86A,bold] #W#{?window_zoomed_flag,*Z,}} #[fg=#C8B86A,bg=#202023,nobold,noitalics,nounderscore]"
  set-window-option -g window-status-format "#[fg=#202023,bg=#2C2C30,noitalics]#[fg=#E3E1DB,bg=#2C2C30] #I #[fg=#E3E1DB,bg=#2C2C30] #W#{?window_zoomed_flag,*Z,}} #[fg=#2C2C30,bg=#202023,noitalics]"
  set-window-option -g window-status-separator ""
}

# vim: set ft=tmux tw=0:
