#!/bin/bash

if [[ $1 == --ssh ]]; then
  # Go in directly with `ssh`.
  ssh github-codespaces
elif [[ $# -eq 1 && "$1" = tail ]]; then
  gh cs ssh -- tail -f /root/codespaces-post-start.log
elif [[ $# -eq 1 && "$1" = create ]]; then
  gh cs create --status --repo github/github --branch master
elif [[ $# -gt 0 ]]; then
  # Forward arguments, so callers can do eg. `gg cs list` etc.
  gh cs "$@"
else
  gh cs ssh --profile github-codespaces
fi
