#!/bin/zsh

source $HOME/.zsh/functions

if ! command -v safe-ruby &> /dev/null; then
  ROOT=$(git root)
  if [ -x "$ROOT/bin/safe-ruby" ]; then
    export PATH="$PATH:$ROOT/bin"
  fi
fi

SCRIPT=script/generate-service-files.rb

if git root test -x $SCRIPT 2> /dev/null; then
  git root $SCRIPT "$@"
else
  echo "error: couldn't find $SCRIPT"
  exit 1
fi
