#!/bin/sh

# Perform daily builds of portal codebases.
if ! ssh-add -l > /dev/null; then
  ssh-add ~/.ssh/id_rsa_2048b_20180102
fi

parallel -v --halt-on-error soon,fail=1 'cd {} && git remote update --prune && git checkout master && git pull --ff-only origin master' ::: ~/code/portal{,-ee}/liferay-binaries-cache-2017 && \
parallel -v --halt-on-error soon,fail=1 'cd {} && git remote update --prune && git checkout master && git pull --ff-only upstream master' ::: ~/code/portal{/liferay-portal,-ee/liferay-portal-ee} && \
parallel -v --halt-on-error soon,fail=1 --line-buffer 'set -o pipefail; cd {} && ant all 2>&1 | tee $PWD/ant-$(basename $(dirname {})).out && git tag "daily/good/$(date +%Y-%m-%d)" && git tag -f daily/good/latest' ::: ~/code/portal{/liferay-portal,-ee/liferay-portal-ee}
