#!/bin/sh

echo "Usage: portool <subcommand> [...arguments]"
echo
echo "Subcommands:"
echo "  daily                  ☀️  run daily builds"
echo "  help                   🤷 show this help"
echo "  node                   🥝 run portal version of node"
echo "  nuke                   ☠️  aggressively clean database, state etc"
echo "  pause                  ⏸  pause the daily build"
echo "  renice                 🐤 renice the daily build"
echo "  resume                 ▶️  resume the daily build"
echo "  restart                🔄 restart the server"
echo "  run [dev|prod]         🚜 run the server"
echo "  sf                     🖌  format source"
echo "  stop                   🛑  stop the server"
echo "  tail                   📃 tail the daily build log"
echo "  yarn                   📦 run Yarn with portal version of node"
