#!/bin/bash

NUKE_LEVEL=0

while (( "$#" )); do
  case "$1" in
    -f)
      NUKE_LEVEL=$(($NUKE_LEVEL + 1))
      ;;
    -ff)
      NUKE_LEVEL=$(($NUKE_LEVEL + 2))
      ;;
    -ff*)
      NUKE_LEVEL=$(($NUKE_LEVEL + 3))
      ;;
  esac

  shift
done

if [[ $NUKE_LEVEL == 0 ]]; then
  echo "☠️  Run with \"-f\" to indicate desired level of nuking:"
  echo
  echo "  -f: truncate database"
  echo "  -ff: truncate database, kill caches"
  echo "  -fff: truncate database, kill caches, \"git clean\""
  echo
fi

if [[ $NUKE_LEVEL > 0 ]]; then
  echo "☠️ Deleting db..."

  echo "set foreign_key_checks=1;" | (echo "select concat('drop table if exists ', table_name, ';') from information_schema.tables where table_schema='lportal_master';" | mysql -u root -B | tail -n +2 && cat;) | (echo "set foreign_key_checks=0;" && cat;) | mysql -u root lportal_master
fi

if [[ $NUKE_LEVEL > 1 ]]; then
  echo "☠️ Cleaning up temporary files..."

  rm -r ~/code/portal/bundles/osgi/state \
        ~/code/portal/bundles/data \
        ~/code/portal/bundles/tomcat-9.0.17/work
fi

if [[ $NUKE_LEVEL > 2 ]]; then
  echo "☠️ \"git clean\"-ing..."

  parallel -v --halt-on-error soon,fail=1 --line-buffer 'cd {} && git clean -fdx' ::: ~/code/portal{/liferay-portal,-ee/liferay-portal-ee}
fi
