#!/bin/bash

# "Installs" a copy of liferay-portal config files.

set -e

PROPERTIES="${BASH_SOURCE%/*}/properties"
BUNDLES="$HOME/code/portal/bundles"
PORTAL="$HOME/code/portal/liferay-portal"

mkdir -p "$BUNDLES" "$PORTAL"

copy() {
  SOURCE=$1
  DEST=$2

  cat <(echo "# vim: set nomodifiable : edit $SOURCE instead then run \`portool setup\`, or use \`:set modifiable\` to force."; echo) "$SOURCE" > "$DEST"
}

copy "$PROPERTIES/portal-ext.properties.dev" "$BUNDLES/portal-ext.properties.dev"
copy "$PROPERTIES/portal-ext.properties.prod" "$BUNDLES/portal-ext.properties.prod"

ln -sf "$BUNDLES/portal-ext.properties.dev" "$BUNDLES/portal-ext.properties"

copy "$PROPERTIES/build.properties" "$PORTAL/build.$USER.properties"
