# vim:ft=kitty

## name:     base16 Arroz con Dulce
## author:   Richard Martinez
## license:  MIT
## upstream: https://github.com/tinted-theming/tinted-terminal
## blurb:    Coconut cream, rice, cinnamon, clove, toasted sugar, and raisin tones inspired by Puerto Rican arroz con dulce.

# Scheme name: base16 Arroz con Dulce
# Scheme author: Richard Martinez
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)

# The basic colors
background #FFF8E7
foreground #4A2C20
selection_background #4A2C20
selection_foreground #EAD6B8

# Cursor colors
cursor #4A2C20
cursor_text_color #FFF8E7

# URL underline color when hovering with mouse
url_color #765B45

# Kitty window border colors
active_border_color #C8A77A
inactive_border_color #F7EBD3

# OS Window titlebar colors
wayland_titlebar_color #FFF8E7
macos_titlebar_color #FFF8E7

# Tab bar colors
active_tab_background #FFF8E7
active_tab_foreground #4A2C20
inactive_tab_background #F7EBD3
inactive_tab_foreground #765B45
tab_bar_background #F7EBD3

# The 16 terminal colors
# normal
color0 #FFF8E7
color1 #A11D48
color2 #A2380C
color3 #855500
color4 #5940A0
color5 #8C1F68
color6 #98263E
color7 #4A2C20

# bright
color8 #C8A77A
color9 #A11D48
color10 #A2380C
color11 #855500
color12 #5940A0
color13 #8C1F68
color14 #98263E
color15 #21110B

# extended base16 colors
color16 #A3470A
color17 #653221
color18 #F7EBD3
color19 #EAD6B8
color20 #765B45
color21 #321C14
