# vim:ft=kitty

## name:     base16 Arroz con Dulce Dark
## author:   Richard Martinez
## license:  MIT
## upstream: https://github.com/tinted-theming/tinted-terminal
## blurb:    A dark cocoa and clove variation of Arroz con Dulce with coconut cream, cinnamon, toasted sugar, and raisin accents.

# Scheme name: base16 Arroz con Dulce Dark
# Scheme author: Richard Martinez
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)

# The basic colors
background #21140F
foreground #F2DFC0
selection_background #F2DFC0
selection_foreground #3B241A

# Cursor colors
cursor #F2DFC0
cursor_text_color #21140F

# URL underline color when hovering with mouse
url_color #C8A77A

# Kitty window border colors
active_border_color #A98568
inactive_border_color #2C1A13

# OS Window titlebar colors
wayland_titlebar_color #21140F
macos_titlebar_color #21140F

# Tab bar colors
active_tab_background #21140F
active_tab_foreground #F2DFC0
inactive_tab_background #2C1A13
inactive_tab_foreground #C8A77A
tab_bar_background #2C1A13

# The 16 terminal colors
# normal
color0 #21140F
color1 #E07A8A
color2 #D47A50
color3 #D9A441
color4 #B99AC8
color5 #D58AB4
color6 #D98276
color7 #F2DFC0

# bright
color8 #A98568
color9 #E07A8A
color10 #D47A50
color11 #D9A441
color12 #B99AC8
color13 #D58AB4
color14 #D98276
color15 #FFF8E7

# extended base16 colors
color16 #E68A4A
color17 #B97755
color18 #2C1A13
color19 #3B241A
color20 #C8A77A
color21 #F8EBD3
