# vim:ft=kitty

## name:     base16 Brasa
## author:   Teshre
## license:  MIT
## upstream: https://github.com/tinted-theming/tinted-terminal
## blurb:    (no description provided)

# Scheme name: base16 Brasa
# Scheme author: Teshre
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)

# The basic colors
background #1A0F0A
foreground #F0D8C0
selection_background #F0D8C0
selection_foreground #45261A

# Cursor colors
cursor #F0D8C0
cursor_text_color #1A0F0A

# URL underline color when hovering with mouse
url_color #B59D88

# Kitty window border colors
active_border_color #7A6150
inactive_border_color #2B1C14

# OS Window titlebar colors
wayland_titlebar_color #1A0F0A
macos_titlebar_color #1A0F0A

# Tab bar colors
active_tab_background #1A0F0A
active_tab_foreground #F0D8C0
inactive_tab_background #2B1C14
inactive_tab_foreground #B59D88
tab_bar_background #2B1C14

# The 16 terminal colors
# normal
color0 #1A0F0A
color1 #F2685A
color2 #B8C24A
color3 #F0B23A
color4 #9AA6E0
color5 #E68AA2
color6 #6BC8B8
color7 #F0D8C0

# bright
color8 #7A6150
color9 #F2685A
color10 #B8C24A
color11 #F0B23A
color12 #9AA6E0
color13 #E68AA2
color14 #6BC8B8
color15 #FBEAD8

# extended base16 colors
color16 #FF7A4D
color17 #5A3A28
color18 #2B1C14
color19 #45261A
color20 #B59D88
color21 #F6E1CC
