# vim:ft=kitty

## name:     base16 Cacao
## author:   Teshre
## license:  MIT
## upstream: https://github.com/tinted-theming/tinted-terminal
## blurb:    (no description provided)

# Scheme name: base16 Cacao
# Scheme author: Teshre
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)

# The basic colors
background #160F0C
foreground #E8D6C4
selection_background #E8D6C4
selection_foreground #3A281E

# Cursor colors
cursor #E8D6C4
cursor_text_color #160F0C

# URL underline color when hovering with mouse
url_color #AF9B8B

# Kitty window border colors
active_border_color #766052
inactive_border_color #241913

# OS Window titlebar colors
wayland_titlebar_color #160F0C
macos_titlebar_color #160F0C

# Tab bar colors
active_tab_background #160F0C
active_tab_foreground #E8D6C4
inactive_tab_background #241913
inactive_tab_foreground #AF9B8B
tab_bar_background #241913

# The 16 terminal colors
# normal
color0 #160F0C
color1 #E0705C
color2 #9AC97A
color3 #E8A84A
color4 #A89AD0
color5 #CE8AB0
color6 #74C8B0
color7 #E8D6C4

# bright
color8 #766052
color9 #E0705C
color10 #9AC97A
color11 #E8A84A
color12 #A89AD0
color13 #CE8AB0
color14 #74C8B0
color15 #F4E6D6

# extended base16 colors
color16 #C77B4A
color17 #4E382A
color18 #241913
color19 #3A281E
color20 #AF9B8B
color21 #EEDECD
