# vim:ft=kitty

## name:     base24 Cerulean Signal Light
## author:   Aaron Colichia (https://aaron.colichia.org/)
## license:  MIT
## upstream: https://github.com/tinted-theming/tinted-terminal
## blurb:    Low-glare cerulean interface theme with restrained neon-pink signal accents; light compatibility palette.

# Scheme name: base24 Cerulean Signal Light
# Scheme author: Aaron Colichia (https://aaron.colichia.org/)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)

# The basic colors
background #f7f9fc
foreground #232b38
selection_background #232b38
selection_foreground #dde7f1

# Cursor colors
cursor #232b38
cursor_text_color #f7f9fc

# URL underline color when hovering with mouse
url_color #566579

# Kitty window border colors
active_border_color #637287
inactive_border_color #eef4fb

# OS Window titlebar colors
wayland_titlebar_color #f7f9fc
macos_titlebar_color #f7f9fc

# Tab bar colors
active_tab_background #f7f9fc
active_tab_foreground #232b38
inactive_tab_background #eef4fb
inactive_tab_foreground #566579
tab_bar_background #eef4fb

# The 16 terminal colors
# normal
color0 #f7f9fc
color1 #b4233d
color2 #17795e
color3 #6f6300
color4 #006fa8
color5 #a0007d
color6 #00727e
color7 #232b38

# bright
color8 #637287
color9 #c7354d
color10 #247b4e
color11 #7b6500
color12 #0078b5
color13 #b5149e
color14 #007787
color15 #141d2a

# extended base16 colors
color16 #9a4f00
color17 #7a4e3c
color18 #eef4fb
color19 #dde7f1
color20 #566579
color21 #202b3a
