# vim:ft=kitty

## name:     base16 Embers Light
## author:   Jannik Siebert (https://github.com/janniks)
## license:  MIT
## upstream: https://github.com/tinted-theming/tinted-terminal
## blurb:    (no description provided)

# Scheme name: base16 Embers Light
# Scheme author: Jannik Siebert (https://github.com/janniks)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)

# The basic colors
background #dbd6d1
foreground #433b32
selection_background #433b32
selection_foreground #a39a90

# Cursor colors
cursor #433b32
cursor_text_color #dbd6d1

# URL underline color when hovering with mouse
url_color #5a5047

# Kitty window border colors
active_border_color #8a8075
inactive_border_color #beb6ae

# OS Window titlebar colors
wayland_titlebar_color #dbd6d1
macos_titlebar_color #dbd6d1

# Tab bar colors
active_tab_background #dbd6d1
active_tab_foreground #433b32
inactive_tab_background #beb6ae
inactive_tab_foreground #5a5047
tab_bar_background #beb6ae

# The 16 terminal colors
# normal
color0 #dbd6d1
color1 #826d57
color2 #57826d
color3 #6d8257
color4 #6d5782
color5 #82576d
color6 #576d82
color7 #433b32

# bright
color8 #8a8075
color9 #826d57
color10 #57826d
color11 #6d8257
color12 #6d5782
color13 #82576d
color14 #576d82
color15 #16130f

# extended base16 colors
color16 #828257
color17 #825757
color18 #beb6ae
color19 #a39a90
color20 #5a5047
color21 #2c2620
