# vim:ft=kitty

## name:     base16 Everforest Light (Hard)
## author:   Márcio Sobel (https://github.com/marciosobel)
## license:  MIT
## upstream: https://github.com/tinted-theming/tinted-terminal
## blurb:    (no description provided)

# Scheme name: base16 Everforest Light (Hard)
# Scheme author: Márcio Sobel (https://github.com/marciosobel)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)

# The basic colors
background #fffbef
foreground #5c6a72
selection_background #5c6a72
selection_foreground #edeada

# Cursor colors
cursor #5c6a72
cursor_text_color #fffbef

# URL underline color when hovering with mouse
url_color #829181

# Kitty window border colors
active_border_color #939f91
inactive_border_color #f8f5e4

# OS Window titlebar colors
wayland_titlebar_color #fffbef
macos_titlebar_color #fffbef

# Tab bar colors
active_tab_background #fffbef
active_tab_foreground #5c6a72
inactive_tab_background #f8f5e4
inactive_tab_foreground #829181
tab_bar_background #f8f5e4

# The 16 terminal colors
# normal
color0 #fffbef
color1 #f85552
color2 #8da101
color3 #dfa000
color4 #3a94c5
color5 #df69ba
color6 #35a77c
color7 #5c6a72

# bright
color8 #939f91
color9 #f85552
color10 #8da101
color11 #dfa000
color12 #3a94c5
color13 #df69ba
color14 #35a77c
color15 #272e33

# extended base16 colors
color16 #f57d26
color17 #829181
color18 #f8f5e4
color19 #edeada
color20 #829181
color21 #414b50
