# vim:ft=kitty

## name:     base24 Github Dark Dimmed
## author:   Tinted Theming (https://github.com/tinted-theming)
## license:  MIT
## upstream: https://github.com/tinted-theming/tinted-terminal
## blurb:    (no description provided)

# Scheme name: base24 Github Dark Dimmed
# Scheme author: Tinted Theming (https://github.com/tinted-theming)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)

# The basic colors
background #22272e
foreground #adbac7
selection_background #adbac7
selection_foreground #545d68

# Cursor colors
cursor #adbac7
cursor_text_color #22272e

# URL underline color when hovering with mouse
url_color #768390

# Kitty window border colors
active_border_color #636e7b
inactive_border_color #2d333b

# OS Window titlebar colors
wayland_titlebar_color #22272e
macos_titlebar_color #22272e

# Tab bar colors
active_tab_background #22272e
active_tab_foreground #adbac7
inactive_tab_background #2d333b
inactive_tab_foreground #768390
tab_bar_background #2d333b

# The 16 terminal colors
# normal
color0 #22272e
color1 #f69d50
color2 #96d0ff
color3 #ae7c14
color4 #dcbdfb
color5 #f47067
color6 #8ddb8c
color7 #adbac7

# bright
color8 #636e7b
color9 #f47067
color10 #57ab5a
color11 #c69026
color12 #539bf5
color13 #b083f0
color14 #33b3ae
color15 #ffffff

# extended base16 colors
color16 #6cb6ff
color17 #ff938a
color18 #2d333b
color19 #545d68
color20 #768390
color21 #cdd9e5
