# vim:ft=kitty

## name:     base16 Kissa Latte
## author:   rwendell (https://github.com/rwendell/kissa)
## license:  MIT
## upstream: https://github.com/tinted-theming/tinted-terminal
## blurb:    (no description provided)

# Scheme name: base16 Kissa Latte
# Scheme author: rwendell (https://github.com/rwendell/kissa)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)

# The basic colors
background #F5F4F0
foreground #1F1C16
selection_background #1F1C16
selection_foreground #D5D2CB

# Cursor colors
cursor #1F1C16
cursor_text_color #F5F4F0

# URL underline color when hovering with mouse
url_color #746C62

# Kitty window border colors
active_border_color #91887D
inactive_border_color #E8E7E3

# OS Window titlebar colors
wayland_titlebar_color #F5F4F0
macos_titlebar_color #F5F4F0

# Tab bar colors
active_tab_background #F5F4F0
active_tab_foreground #1F1C16
inactive_tab_background #E8E7E3
inactive_tab_foreground #746C62
tab_bar_background #E8E7E3

# The 16 terminal colors
# normal
color0 #F5F4F0
color1 #9E3E3E
color2 #387050
color3 #7D6820
color4 #3468A8
color5 #6438A0
color6 #287070
color7 #1F1C16

# bright
color8 #91887D
color9 #9E3E3E
color10 #387050
color11 #7D6820
color12 #3468A8
color13 #6438A0
color14 #287070
color15 #FEFCFA

# extended base16 colors
color16 #8F5D22
color17 #943A68
color18 #E8E7E3
color19 #D5D2CB
color20 #746C62
color21 #6E6459
