# vim:ft=kitty

## name:     base16 Kissa Macchiato
## author:   rwendell (https://github.com/rwendell/kissa)
## license:  MIT
## upstream: https://github.com/tinted-theming/tinted-terminal
## blurb:    (no description provided)

# Scheme name: base16 Kissa Macchiato
# Scheme author: rwendell (https://github.com/rwendell/kissa)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)

# The basic colors
background #1F1C16
foreground #FAF0E6
selection_background #FAF0E6
selection_foreground #47443F

# Cursor colors
cursor #FAF0E6
cursor_text_color #1F1C16

# URL underline color when hovering with mouse
url_color #D4C4A8

# Kitty window border colors
active_border_color #B8A48C
inactive_border_color #35322D

# OS Window titlebar colors
wayland_titlebar_color #1F1C16
macos_titlebar_color #1F1C16

# Tab bar colors
active_tab_background #1F1C16
active_tab_foreground #FAF0E6
inactive_tab_background #35322D
inactive_tab_foreground #D4C4A8
tab_bar_background #35322D

# The 16 terminal colors
# normal
color0 #1F1C16
color1 #E87777
color2 #8CB870
color3 #EAC67A
color4 #7FA8D4
color5 #B094CC
color6 #6AB8B0
color7 #FAF0E6

# bright
color8 #B8A48C
color9 #E87777
color10 #8CB870
color11 #EAC67A
color12 #7FA8D4
color13 #B094CC
color14 #6AB8B0
color15 #FEF4E4

# extended base16 colors
color16 #DA9050
color17 #CC88AA
color18 #35322D
color19 #47443F
color20 #D4C4A8
color21 #E8D5B7
