# vim:ft=kitty

## name:     base16 Mezcal
## author:   Teshre
## license:  MIT
## upstream: https://github.com/tinted-theming/tinted-terminal
## blurb:    (no description provided)

# Scheme name: base16 Mezcal
# Scheme author: Teshre
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)

# The basic colors
background #13110E
foreground #E0D8C8
selection_background #E0D8C8
selection_foreground #36301E

# Cursor colors
cursor #E0D8C8
cursor_text_color #13110E

# URL underline color when hovering with mouse
url_color #A79E8C

# Kitty window border colors
active_border_color #6E6450
inactive_border_color #221F14

# OS Window titlebar colors
wayland_titlebar_color #13110E
macos_titlebar_color #13110E

# Tab bar colors
active_tab_background #13110E
active_tab_foreground #E0D8C8
inactive_tab_background #221F14
inactive_tab_foreground #A79E8C
tab_bar_background #221F14

# The 16 terminal colors
# normal
color0 #13110E
color1 #DA6E54
color2 #A8B84A
color3 #D9A441
color4 #8AA6C0
color5 #C28AA8
color6 #6FC8AE
color7 #E0D8C8

# bright
color8 #6E6450
color9 #DA6E54
color10 #A8B84A
color11 #D9A441
color12 #8AA6C0
color13 #C28AA8
color14 #6FC8AE
color15 #F2EAD6

# extended base16 colors
color16 #D9A441
color17 #4E462C
color18 #221F14
color19 #36301E
color20 #A79E8C
color21 #E9E1CF
