# vim:ft=kitty

## name:     base16 Noche
## author:   Teshre
## license:  MIT
## upstream: https://github.com/tinted-theming/tinted-terminal
## blurb:    (no description provided)

# Scheme name: base16 Noche
# Scheme author: Teshre
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)

# The basic colors
background #0C0E16
foreground #CBD4EC
selection_background #CBD4EC
selection_foreground #232A40

# Cursor colors
cursor #CBD4EC
cursor_text_color #0C0E16

# URL underline color when hovering with mouse
url_color #939BB2

# Kitty window border colors
active_border_color #5A6178
inactive_border_color #181C2C

# OS Window titlebar colors
wayland_titlebar_color #0C0E16
macos_titlebar_color #0C0E16

# Tab bar colors
active_tab_background #0C0E16
active_tab_foreground #CBD4EC
inactive_tab_background #181C2C
inactive_tab_foreground #939BB2
tab_bar_background #181C2C

# The 16 terminal colors
# normal
color0 #0C0E16
color1 #E2727E
color2 #7CC596
color3 #D8C062
color4 #7AA0E8
color5 #B79AE0
color6 #6DD8D0
color7 #CBD4EC

# bright
color8 #5A6178
color9 #E2727E
color10 #7CC596
color11 #D8C062
color12 #7AA0E8
color13 #B79AE0
color14 #6DD8D0
color15 #E6ECFA

# extended base16 colors
color16 #82A6E0
color17 #3A4260
color18 #181C2C
color19 #232A40
color20 #939BB2
color21 #D9E0F3
