# vim:ft=kitty

## name:     base16 Ocote
## author:   Teshre
## license:  MIT
## upstream: https://github.com/tinted-theming/tinted-terminal
## blurb:    (no description provided)

# Scheme name: base16 Ocote
# Scheme author: Teshre
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)

# The basic colors
background #14100C
foreground #E7DCC6
selection_background #E7DCC6
selection_foreground #3A2E1C

# Cursor colors
cursor #E7DCC6
cursor_text_color #14100C

# URL underline color when hovering with mouse
url_color #A99F8D

# Kitty window border colors
active_border_color #6B6253
inactive_border_color #211B13

# OS Window titlebar colors
wayland_titlebar_color #14100C
macos_titlebar_color #14100C

# Tab bar colors
active_tab_background #14100C
active_tab_foreground #E7DCC6
inactive_tab_background #211B13
inactive_tab_foreground #A99F8D
tab_bar_background #211B13

# The 16 terminal colors
# normal
color0 #14100C
color1 #E8635A
color2 #7DC97A
color3 #E8B43A
color4 #82A6E0
color5 #C58AE0
color6 #6DD8C8
color7 #E7DCC6

# bright
color8 #6B6253
color9 #E8635A
color10 #7DC97A
color11 #E8B43A
color12 #82A6E0
color13 #C58AE0
color14 #6DD8C8
color15 #FAF6EC

# extended base16 colors
color16 #E8843A
color17 #4A3E2C
color18 #211B13
color19 #3A2E1C
color20 #A99F8D
color21 #F1E9D9
