# vim:ft=kitty

## name:     base16 Papel
## author:   Teshre
## license:  MIT
## upstream: https://github.com/tinted-theming/tinted-terminal
## blurb:    (no description provided)

# Scheme name: base16 Papel
# Scheme author: Teshre
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)

# The basic colors
background #F5EFE2
foreground #3A2E20
selection_background #3A2E20
selection_foreground #E0D0AC

# Cursor colors
cursor #3A2E20
cursor_text_color #F5EFE2

# URL underline color when hovering with mouse
url_color #6A5D4B

# Kitty window border colors
active_border_color #9A8C76
inactive_border_color #8E8576

# OS Window titlebar colors
wayland_titlebar_color #F5EFE2
macos_titlebar_color #F5EFE2

# Tab bar colors
active_tab_background #F5EFE2
active_tab_foreground #3A2E20
inactive_tab_background #8E8576
inactive_tab_foreground #6A5D4B
tab_bar_background #8E8576

# The 16 terminal colors
# normal
color0 #F5EFE2
color1 #C0392B
color2 #5E7A28
color3 #A8761A
color4 #2C6CA0
color5 #9B4D8E
color6 #2A8A7A
color7 #3A2E20

# bright
color8 #9A8C76
color9 #C0392B
color10 #5E7A28
color11 #A8761A
color12 #2C6CA0
color13 #9B4D8E
color14 #2A8A7A
color15 #EFE8D8

# extended base16 colors
color16 #C25C1F
color17 #6E6353
color18 #8E8576
color19 #E0D0AC
color20 #6A5D4B
color21 #958B7C
