# vim:ft=kitty

## name:     base16 Swamp Dark
## author:   Masroof Maindak (https://github.com/masroof-maindak)
## license:  MIT
## upstream: https://github.com/tinted-theming/tinted-terminal
## blurb:    (no description provided)

# Scheme name: base16 Swamp Dark
# Scheme author: Masroof Maindak (https://github.com/masroof-maindak)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)

# The basic colors
background #242015
foreground #D2C3A4
selection_background #D2C3A4
selection_foreground #4D3F32

# Cursor colors
cursor #D2C3A4
cursor_text_color #242015

# URL underline color when hovering with mouse
url_color #B8A58C

# Kitty window border colors
active_border_color #5F4E41
inactive_border_color #3A3124

# OS Window titlebar colors
wayland_titlebar_color #242015
macos_titlebar_color #242015

# Tab bar colors
active_tab_background #242015
active_tab_foreground #D2C3A4
inactive_tab_background #3A3124
inactive_tab_foreground #B8A58C
tab_bar_background #3A3124

# The 16 terminal colors
# normal
color0 #242015
color1 #DB930D
color2 #7A7653
color3 #A82D56
color4 #C1666B
color5 #91506C
color6 #DB930D
color7 #D2C3A4

# bright
color8 #5F4E41
color9 #DB930D
color10 #7A7653
color11 #A82D56
color12 #C1666B
color13 #91506C
color14 #DB930D
color15 #F1E9D0

# extended base16 colors
color16 #EBE0BB
color17 #61A0A8
color18 #3A3124
color19 #4D3F32
color20 #B8A58C
color21 #EBE0BB
