# vim:ft=kitty

## name:     base16 Swamp Light
## author:   Masroof Maindak (https://github.com/masroof-maindak)
## license:  MIT
## upstream: https://github.com/tinted-theming/tinted-terminal
## blurb:    (no description provided)

# Scheme name: base16 Swamp Light
# Scheme author: Masroof Maindak (https://github.com/masroof-maindak)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)

# The basic colors
background #F1E3D1
foreground #64513E
selection_background #64513E
selection_foreground #C9B9A7

# Cursor colors
cursor #64513E
cursor_text_color #F1E3D1

# URL underline color when hovering with mouse
url_color #A0907D

# Kitty window border colors
active_border_color #B5A492
inactive_border_color #DDCEBC

# OS Window titlebar colors
wayland_titlebar_color #F1E3D1
macos_titlebar_color #F1E3D1

# Tab bar colors
active_tab_background #F1E3D1
active_tab_foreground #64513E
inactive_tab_background #DDCEBC
inactive_tab_foreground #A0907D
tab_bar_background #DDCEBC

# The 16 terminal colors
# normal
color0 #F1E3D1
color1 #D09700
color2 #908D6A
color3 #993333
color4 #BF7979
color5 #9E5581
color6 #d09700
color7 #64513E

# bright
color8 #B5A492
color9 #D09700
color10 #908D6A
color11 #993333
color12 #BF7979
color13 #9E5581
color14 #d09700
color15 #8C7B68

# extended base16 colors
color16 #64513E
color17 #75858C
color18 #DDCEBC
color19 #C9B9A7
color20 #A0907D
color21 #786653
